# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TPS07A_meshbestGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1864, 981)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LastInfo = QtWidgets.QLabel(self.centralwidget)
        self.LastInfo.setMinimumSize(QtCore.QSize(300, 0))
        self.LastInfo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LastInfo.setTextFormat(QtCore.Qt.AutoText)
        self.LastInfo.setObjectName("LastInfo")
        self.horizontalLayout.addWidget(self.LastInfo)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.TPSStateText = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.TPSStateText.setFont(font)
        self.TPSStateText.setObjectName("TPSStateText")
        self.horizontalLayout.addWidget(self.TPSStateText)
        self.Current = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.Current.setMinimumSize(QtCore.QSize(0, 0))
        self.Current.setAutoFillBackground(False)
        self.Current.setFrame(True)
        self.Current.setAlignment(QtCore.Qt.AlignCenter)
        self.Current.setReadOnly(True)
        self.Current.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Current.setSpecialValueText("")
        self.Current.setAccelerated(False)
        self.Current.setKeyboardTracking(True)
        self.Current.setPrefix("")
        self.Current.setDecimals(3)
        self.Current.setMaximum(1000.0)
        self.Current.setProperty("value", 500.0)
        self.Current.setObjectName("Current")
        self.horizontalLayout.addWidget(self.Current)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.Energy = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.Energy.setAlignment(QtCore.Qt.AlignCenter)
        self.Energy.setReadOnly(True)
        self.Energy.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Energy.setPrefix("")
        self.Energy.setDecimals(3)
        self.Energy.setMinimum(4000.0)
        self.Energy.setMaximum(20000.0)
        self.Energy.setObjectName("Energy")
        self.horizontalLayout.addWidget(self.Energy)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.beamlineflux = QtWidgets.QLabel(self.centralwidget)
        self.beamlineflux.setInputMethodHints(QtCore.Qt.ImhNone)
        self.beamlineflux.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.beamlineflux.setFrameShadow(QtWidgets.QFrame.Plain)
        self.beamlineflux.setLineWidth(1)
        self.beamlineflux.setMidLineWidth(0)
        self.beamlineflux.setTextFormat(QtCore.Qt.AutoText)
        self.beamlineflux.setScaledContents(False)
        self.beamlineflux.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.beamlineflux.setObjectName("beamlineflux")
        self.horizontalLayout.addWidget(self.beamlineflux)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout.addWidget(self.label_24)
        self.timetoinj = QtWidgets.QLabel(self.centralwidget)
        self.timetoinj.setInputMethodHints(QtCore.Qt.ImhNone)
        self.timetoinj.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.timetoinj.setFrameShadow(QtWidgets.QFrame.Plain)
        self.timetoinj.setLineWidth(1)
        self.timetoinj.setMidLineWidth(0)
        self.timetoinj.setTextFormat(QtCore.Qt.AutoText)
        self.timetoinj.setScaledContents(False)
        self.timetoinj.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.timetoinj.setObjectName("timetoinj")
        self.horizontalLayout.addWidget(self.timetoinj)
        self.Abort = QtWidgets.QPushButton(self.centralwidget)
        self.Abort.setStyleSheet("background:rgb(250, 0, 0)")
        self.Abort.setObjectName("Abort")
        self.horizontalLayout.addWidget(self.Abort)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Active = QtWidgets.QPushButton(self.centralwidget)
        self.Active.setMinimumSize(QtCore.QSize(140, 30))
        self.Active.setCheckable(True)
        self.Active.setChecked(False)
        self.Active.setAutoRepeat(False)
        self.Active.setAutoExclusive(False)
        self.Active.setAutoDefault(False)
        self.Active.setDefault(True)
        self.Active.setObjectName("Active")
        self.horizontalLayout.addWidget(self.Active)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 3)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.tab_1)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Focus_pos_s = QtWidgets.QPushButton(self.tab_2)
        self.Focus_pos_s.setAutoRepeat(False)
        self.Focus_pos_s.setObjectName("Focus_pos_s")
        self.gridLayout_4.addWidget(self.Focus_pos_s, 13, 2, 1, 1)
        self.StartRaster = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartRaster.sizePolicy().hasHeightForWidth())
        self.StartRaster.setSizePolicy(sizePolicy)
        self.StartRaster.setMinimumSize(QtCore.QSize(0, 30))
        self.StartRaster.setIconSize(QtCore.QSize(16, 16))
        self.StartRaster.setObjectName("StartRaster")
        self.gridLayout_4.addWidget(self.StartRaster, 1, 2, 1, 2)
        self.Focus_neg_l = QtWidgets.QPushButton(self.tab_2)
        self.Focus_neg_l.setObjectName("Focus_neg_l")
        self.gridLayout_4.addWidget(self.Focus_neg_l, 13, 0, 1, 1)
        self.Focus_pos_l = QtWidgets.QPushButton(self.tab_2)
        self.Focus_pos_l.setAutoRepeat(False)
        self.Focus_pos_l.setObjectName("Focus_pos_l")
        self.gridLayout_4.addWidget(self.Focus_pos_l, 13, 3, 1, 1)
        self.Direct_collect = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Direct_collect.sizePolicy().hasHeightForWidth())
        self.Direct_collect.setSizePolicy(sizePolicy)
        self.Direct_collect.setMinimumSize(QtCore.QSize(0, 20))
        self.Direct_collect.setIconSize(QtCore.QSize(16, 16))
        self.Direct_collect.setObjectName("Direct_collect")
        self.gridLayout_4.addWidget(self.Direct_collect, 2, 2, 1, 2)
        self.Raster = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Raster.sizePolicy().hasHeightForWidth())
        self.Raster.setSizePolicy(sizePolicy)
        self.Raster.setMinimumSize(QtCore.QSize(0, 50))
        self.Raster.setIconSize(QtCore.QSize(16, 16))
        self.Raster.setObjectName("Raster")
        self.gridLayout_4.addWidget(self.Raster, 1, 0, 2, 2)
        self.Autocenter = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Autocenter.sizePolicy().hasHeightForWidth())
        self.Autocenter.setSizePolicy(sizePolicy)
        self.Autocenter.setObjectName("Autocenter")
        self.gridLayout_4.addWidget(self.Autocenter, 15, 0, 1, 1)
        self.Zoom1 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Zoom1.sizePolicy().hasHeightForWidth())
        self.Zoom1.setSizePolicy(sizePolicy)
        self.Zoom1.setObjectName("Zoom1")
        self.gridLayout_4.addWidget(self.Zoom1, 9, 0, 1, 1)
        self.pos_10deg = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos_10deg.sizePolicy().hasHeightForWidth())
        self.pos_10deg.setSizePolicy(sizePolicy)
        self.pos_10deg.setObjectName("pos_10deg")
        self.gridLayout_4.addWidget(self.pos_10deg, 10, 2, 1, 1)
        self.pos_90deg = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos_90deg.sizePolicy().hasHeightForWidth())
        self.pos_90deg.setSizePolicy(sizePolicy)
        self.pos_90deg.setObjectName("pos_90deg")
        self.gridLayout_4.addWidget(self.pos_90deg, 10, 3, 1, 1)
        self.Centermode = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Centermode.sizePolicy().hasHeightForWidth())
        self.Centermode.setSizePolicy(sizePolicy)
        self.Centermode.setObjectName("Centermode")
        self.gridLayout_4.addWidget(self.Centermode, 15, 2, 1, 1)
        self.Zoom2 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Zoom2.sizePolicy().hasHeightForWidth())
        self.Zoom2.setSizePolicy(sizePolicy)
        self.Zoom2.setObjectName("Zoom2")
        self.gridLayout_4.addWidget(self.Zoom2, 9, 1, 1, 1)
        self.neg_90deg = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.neg_90deg.sizePolicy().hasHeightForWidth())
        self.neg_90deg.setSizePolicy(sizePolicy)
        self.neg_90deg.setObjectName("neg_90deg")
        self.gridLayout_4.addWidget(self.neg_90deg, 10, 0, 1, 1)
        self.Zoom3 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Zoom3.sizePolicy().hasHeightForWidth())
        self.Zoom3.setSizePolicy(sizePolicy)
        self.Zoom3.setObjectName("Zoom3")
        self.gridLayout_4.addWidget(self.Zoom3, 9, 2, 1, 1)
        self.Zoom4 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Zoom4.sizePolicy().hasHeightForWidth())
        self.Zoom4.setSizePolicy(sizePolicy)
        self.Zoom4.setObjectName("Zoom4")
        self.gridLayout_4.addWidget(self.Zoom4, 9, 3, 1, 1)
        self.Transfermode = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Transfermode.sizePolicy().hasHeightForWidth())
        self.Transfermode.setSizePolicy(sizePolicy)
        self.Transfermode.setObjectName("Transfermode")
        self.gridLayout_4.addWidget(self.Transfermode, 15, 3, 1, 1)
        self.SampleViedo = QtWidgets.QGraphicsView(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SampleViedo.sizePolicy().hasHeightForWidth())
        self.SampleViedo.setSizePolicy(sizePolicy)
        self.SampleViedo.setMinimumSize(QtCore.QSize(320, 256))
        self.SampleViedo.setMaximumSize(QtCore.QSize(1280, 1024))
        self.SampleViedo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SampleViedo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SampleViedo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SampleViedo.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.SampleViedo.setObjectName("SampleViedo")
        self.gridLayout_4.addWidget(self.SampleViedo, 0, 0, 1, 4)
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 14, 0, 1, 4)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 12, 0, 1, 4)
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 8, 0, 1, 4)
        self.Focus_neg_s = QtWidgets.QPushButton(self.tab_2)
        self.Focus_neg_s.setObjectName("Focus_neg_s")
        self.gridLayout_4.addWidget(self.Focus_neg_s, 13, 1, 1, 1)
        self.neg_10deg = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.neg_10deg.sizePolicy().hasHeightForWidth())
        self.neg_10deg.setSizePolicy(sizePolicy)
        self.neg_10deg.setObjectName("neg_10deg")
        self.gridLayout_4.addWidget(self.neg_10deg, 10, 1, 1, 1)
        self.neg_5deg = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.neg_5deg.sizePolicy().hasHeightForWidth())
        self.neg_5deg.setSizePolicy(sizePolicy)
        self.neg_5deg.setObjectName("neg_5deg")
        self.gridLayout_4.addWidget(self.neg_5deg, 11, 0, 1, 1)
        self.neg_1deg = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.neg_1deg.sizePolicy().hasHeightForWidth())
        self.neg_1deg.setSizePolicy(sizePolicy)
        self.neg_1deg.setObjectName("neg_1deg")
        self.gridLayout_4.addWidget(self.neg_1deg, 11, 1, 1, 1)
        self.pos_1deg = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos_1deg.sizePolicy().hasHeightForWidth())
        self.pos_1deg.setSizePolicy(sizePolicy)
        self.pos_1deg.setObjectName("pos_1deg")
        self.gridLayout_4.addWidget(self.pos_1deg, 11, 2, 1, 1)
        self.pos_5deg = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos_5deg.sizePolicy().hasHeightForWidth())
        self.pos_5deg.setSizePolicy(sizePolicy)
        self.pos_5deg.setObjectName("pos_5deg")
        self.gridLayout_4.addWidget(self.pos_5deg, 11, 3, 1, 1)
        self.gridLayout_4.setColumnMinimumWidth(3, 100)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 2, 1)
        self.toolBox = QtWidgets.QToolBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(16777215, 130))
        self.toolBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolBox.setLineWidth(1)
        self.toolBox.setMidLineWidth(0)
        self.toolBox.setObjectName("toolBox")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 214, 70))
        self.page_3.setObjectName("page_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.RootPath = QtWidgets.QLineEdit(self.page_3)
        self.RootPath.setObjectName("RootPath")
        self.gridLayout_12.addWidget(self.RootPath, 0, 0, 1, 1)
        self.RootPath_2 = QtWidgets.QLineEdit(self.page_3)
        self.RootPath_2.setEnabled(False)
        self.RootPath_2.setFrame(True)
        self.RootPath_2.setReadOnly(True)
        self.RootPath_2.setObjectName("RootPath_2")
        self.gridLayout_12.addWidget(self.RootPath_2, 1, 0, 1, 1)
        self.GetDefalutFolder = QtWidgets.QPushButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GetDefalutFolder.sizePolicy().hasHeightForWidth())
        self.GetDefalutFolder.setSizePolicy(sizePolicy)
        self.GetDefalutFolder.setObjectName("GetDefalutFolder")
        self.gridLayout_12.addWidget(self.GetDefalutFolder, 0, 1, 1, 1)
        self.UpdateFolder = QtWidgets.QPushButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UpdateFolder.sizePolicy().hasHeightForWidth())
        self.UpdateFolder.setSizePolicy(sizePolicy)
        self.UpdateFolder.setObjectName("UpdateFolder")
        self.gridLayout_12.addWidget(self.UpdateFolder, 0, 2, 1, 1)
        self.toolBox.addItem(self.page_3, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 1383, 73))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_5.sizePolicy().hasHeightForWidth())
        self.page_5.setSizePolicy(sizePolicy)
        self.page_5.setObjectName("page_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_16 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.gridLayout_10.addWidget(self.label_16, 0, 5, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout_10.addWidget(self.label_14, 0, 0, 1, 1)
        self.ExpouseValue = QtWidgets.QDoubleSpinBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExpouseValue.sizePolicy().hasHeightForWidth())
        self.ExpouseValue.setSizePolicy(sizePolicy)
        self.ExpouseValue.setDecimals(3)
        self.ExpouseValue.setMaximum(100.0)
        self.ExpouseValue.setProperty("value", 0.01)
        self.ExpouseValue.setObjectName("ExpouseValue")
        self.gridLayout_10.addWidget(self.ExpouseValue, 1, 2, 1, 1)
        self.ExpousetimeType = QtWidgets.QComboBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExpousetimeType.sizePolicy().hasHeightForWidth())
        self.ExpousetimeType.setSizePolicy(sizePolicy)
        self.ExpousetimeType.setMinimumSize(QtCore.QSize(110, 0))
        self.ExpousetimeType.setObjectName("ExpousetimeType")
        self.ExpousetimeType.addItem("")
        self.ExpousetimeType.addItem("")
        self.gridLayout_10.addWidget(self.ExpousetimeType, 0, 2, 1, 1)
        self.Attenuation = QtWidgets.QDoubleSpinBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Attenuation.sizePolicy().hasHeightForWidth())
        self.Attenuation.setSizePolicy(sizePolicy)
        self.Attenuation.setObjectName("Attenuation")
        self.gridLayout_10.addWidget(self.Attenuation, 1, 1, 1, 1)
        self.rasterdose = QtWidgets.QDoubleSpinBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rasterdose.sizePolicy().hasHeightForWidth())
        self.rasterdose.setSizePolicy(sizePolicy)
        self.rasterdose.setMinimumSize(QtCore.QSize(0, 0))
        self.rasterdose.setAlignment(QtCore.Qt.AlignCenter)
        self.rasterdose.setReadOnly(True)
        self.rasterdose.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.rasterdose.setDecimals(3)
        self.rasterdose.setObjectName("rasterdose")
        self.gridLayout_10.addWidget(self.rasterdose, 1, 8, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 0, 8, 1, 1)
        self.Distance = QtWidgets.QDoubleSpinBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Distance.sizePolicy().hasHeightForWidth())
        self.Distance.setSizePolicy(sizePolicy)
        self.Distance.setMinimum(140.0)
        self.Distance.setMaximum(1000.0)
        self.Distance.setObjectName("Distance")
        self.gridLayout_10.addWidget(self.Distance, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout_10.addWidget(self.label_13, 0, 1, 1, 1)
        self.selectGridsize = QtWidgets.QComboBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectGridsize.sizePolicy().hasHeightForWidth())
        self.selectGridsize.setSizePolicy(sizePolicy)
        self.selectGridsize.setMaxVisibleItems(11)
        self.selectGridsize.setObjectName("selectGridsize")
        self.selectGridsize.addItem("")
        self.selectGridsize.addItem("")
        self.selectGridsize.addItem("")
        self.selectGridsize.addItem("")
        self.selectGridsize.addItem("")
        self.selectGridsize.addItem("")
        self.selectGridsize.addItem("")
        self.selectGridsize.addItem("")
        self.selectGridsize.addItem("")
        self.selectGridsize.addItem("")
        self.selectGridsize.addItem("")
        self.gridLayout_10.addWidget(self.selectGridsize, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 0, 3, 1, 1)
        self.selectBeamsize = QtWidgets.QComboBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectBeamsize.sizePolicy().hasHeightForWidth())
        self.selectBeamsize.setSizePolicy(sizePolicy)
        self.selectBeamsize.setMaxVisibleItems(11)
        self.selectBeamsize.setObjectName("selectBeamsize")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.gridLayout_10.addWidget(self.selectBeamsize, 1, 4, 1, 1)
        self.selectROI = QtWidgets.QComboBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectROI.sizePolicy().hasHeightForWidth())
        self.selectROI.setSizePolicy(sizePolicy)
        self.selectROI.setMaxVisibleItems(11)
        self.selectROI.setObjectName("selectROI")
        self.selectROI.addItem("")
        self.selectROI.addItem("")
        self.gridLayout_10.addWidget(self.selectROI, 1, 6, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.gridLayout_10.addWidget(self.label_17, 0, 4, 1, 1)
        self.RotationValue = QtWidgets.QDoubleSpinBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RotationValue.sizePolicy().hasHeightForWidth())
        self.RotationValue.setSizePolicy(sizePolicy)
        self.RotationValue.setDecimals(3)
        self.RotationValue.setMaximum(10.0)
        self.RotationValue.setSingleStep(0.1)
        self.RotationValue.setProperty("value", 0.0)
        self.RotationValue.setObjectName("RotationValue")
        self.gridLayout_10.addWidget(self.RotationValue, 1, 5, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 0, 6, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName("label_26")
        self.gridLayout_10.addWidget(self.label_26, 0, 7, 1, 1)
        self.select2scan = QtWidgets.QComboBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select2scan.sizePolicy().hasHeightForWidth())
        self.select2scan.setSizePolicy(sizePolicy)
        self.select2scan.setMaxVisibleItems(11)
        self.select2scan.setObjectName("select2scan")
        self.select2scan.addItem("")
        self.select2scan.addItem("")
        self.gridLayout_10.addWidget(self.select2scan, 1, 7, 1, 1)
        self.gridLayout_10.setColumnStretch(0, 5)
        self.gridLayout_10.setColumnStretch(1, 10)
        self.gridLayout_10.setColumnStretch(2, 10)
        self.gridLayout_10.setColumnStretch(3, 10)
        self.gridLayout_10.setColumnStretch(4, 10)
        self.gridLayout_10.setColumnStretch(5, 5)
        self.gridLayout_10.setColumnStretch(6, 5)
        self.gridLayout_10.setColumnStretch(7, 5)
        self.verticalLayout_7.addLayout(self.gridLayout_10)
        self.toolBox.addItem(self.page_5, "")
        self.gridLayout_5.addWidget(self.toolBox, 0, 2, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.RasterView1 = QtWidgets.QGraphicsView(self.tab_2)
        self.RasterView1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RasterView1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RasterView1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.RasterView1.setViewportUpdateMode(QtWidgets.QGraphicsView.SmartViewportUpdate)
        self.RasterView1.setObjectName("RasterView1")
        self.verticalLayout.addWidget(self.RasterView1)
        self.Overlap_Select_1 = QtWidgets.QComboBox(self.tab_2)
        self.Overlap_Select_1.setObjectName("Overlap_Select_1")
        self.Overlap_Select_1.addItem("")
        self.Overlap_Select_1.addItem("")
        self.Overlap_Select_1.addItem("")
        self.Overlap_Select_1.addItem("")
        self.Overlap_Select_1.addItem("")
        self.Overlap_Select_1.addItem("")
        self.Overlap_Select_1.addItem("")
        self.verticalLayout.addWidget(self.Overlap_Select_1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.view1_opacity = QtWidgets.QSlider(self.tab_2)
        self.view1_opacity.setMaximum(100)
        self.view1_opacity.setProperty("value", 80)
        self.view1_opacity.setOrientation(QtCore.Qt.Horizontal)
        self.view1_opacity.setObjectName("view1_opacity")
        self.horizontalLayout_7.addWidget(self.view1_opacity)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_3.addWidget(self.label_22)
        self.updatelist_1 = QtWidgets.QComboBox(self.tab_2)
        self.updatelist_1.setObjectName("updatelist_1")
        self.updatelist_1.addItem("")
        self.updatelist_1.addItem("")
        self.updatelist_1.addItem("")
        self.updatelist_1.addItem("")
        self.horizontalLayout_3.addWidget(self.updatelist_1)
        self.Generate_position_1 = QtWidgets.QPushButton(self.tab_2)
        self.Generate_position_1.setStyleSheet("QPushButton:checked {\n"
"    background-color:rgb(255, 0, 0)\n"
"}")
        self.Generate_position_1.setCheckable(True)
        self.Generate_position_1.setChecked(False)
        self.Generate_position_1.setObjectName("Generate_position_1")
        self.horizontalLayout_3.addWidget(self.Generate_position_1)
        self.ClearAll_1 = QtWidgets.QPushButton(self.tab_2)
        self.ClearAll_1.setObjectName("ClearAll_1")
        self.horizontalLayout_3.addWidget(self.ClearAll_1)
        self.EditPos_1 = QtWidgets.QPushButton(self.tab_2)
        self.EditPos_1.setCheckable(True)
        self.EditPos_1.setObjectName("EditPos_1")
        self.horizontalLayout_3.addWidget(self.EditPos_1)
        self.MovePos_1 = QtWidgets.QPushButton(self.tab_2)
        self.MovePos_1.setCheckable(True)
        self.MovePos_1.setObjectName("MovePos_1")
        self.horizontalLayout_3.addWidget(self.MovePos_1)
        self.horizontalLayout_3.setStretch(1, 10)
        self.horizontalLayout_3.setStretch(3, 10)
        self.horizontalLayout_3.setStretch(4, 10)
        self.horizontalLayout_3.setStretch(5, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.List_number_1 = QtWidgets.QSpinBox(self.tab_2)
        self.List_number_1.setMaximum(999)
        self.List_number_1.setProperty("value", 10)
        self.List_number_1.setObjectName("List_number_1")
        self.horizontalLayout_2.addWidget(self.List_number_1)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.Threshold_1 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.Threshold_1.setMinimum(-1.0)
        self.Threshold_1.setMaximum(9999.0)
        self.Threshold_1.setProperty("value", 1.0)
        self.Threshold_1.setObjectName("Threshold_1")
        self.horizontalLayout_2.addWidget(self.Threshold_1)
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_2.addWidget(self.label_19)
        self.Min_peak_distance_1 = QtWidgets.QSpinBox(self.tab_2)
        self.Min_peak_distance_1.setMaximum(999)
        self.Min_peak_distance_1.setProperty("value", 0)
        self.Min_peak_distance_1.setObjectName("Min_peak_distance_1")
        self.horizontalLayout_2.addWidget(self.Min_peak_distance_1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.viwe1_move_down = QtWidgets.QPushButton(self.tab_2)
        self.viwe1_move_down.setObjectName("viwe1_move_down")
        self.gridLayout_3.addWidget(self.viwe1_move_down, 2, 1, 1, 1)
        self.viwe1_move_up = QtWidgets.QPushButton(self.tab_2)
        self.viwe1_move_up.setObjectName("viwe1_move_up")
        self.gridLayout_3.addWidget(self.viwe1_move_up, 0, 1, 1, 1)
        self.viwe1_move_right = QtWidgets.QPushButton(self.tab_2)
        self.viwe1_move_right.setAutoRepeat(False)
        self.viwe1_move_right.setObjectName("viwe1_move_right")
        self.gridLayout_3.addWidget(self.viwe1_move_right, 1, 2, 1, 1)
        self.collectAllpos_1 = QtWidgets.QPushButton(self.tab_2)
        self.collectAllpos_1.setObjectName("collectAllpos_1")
        self.gridLayout_3.addWidget(self.collectAllpos_1, 3, 2, 1, 1)
        self.DetailInfo1 = QtWidgets.QPushButton(self.tab_2)
        self.DetailInfo1.setObjectName("DetailInfo1")
        self.gridLayout_3.addWidget(self.DetailInfo1, 3, 0, 1, 1)
        self.viwe1_move_left = QtWidgets.QPushButton(self.tab_2)
        self.viwe1_move_left.setObjectName("viwe1_move_left")
        self.gridLayout_3.addWidget(self.viwe1_move_left, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_5.addLayout(self.verticalLayout, 1, 2, 3, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.RasterView2 = QtWidgets.QGraphicsView(self.tab_2)
        self.RasterView2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RasterView2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RasterView2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.RasterView2.setViewportUpdateMode(QtWidgets.QGraphicsView.SmartViewportUpdate)
        self.RasterView2.setObjectName("RasterView2")
        self.verticalLayout_3.addWidget(self.RasterView2)
        self.Overlap_Select_2 = QtWidgets.QComboBox(self.tab_2)
        self.Overlap_Select_2.setObjectName("Overlap_Select_2")
        self.Overlap_Select_2.addItem("")
        self.Overlap_Select_2.addItem("")
        self.Overlap_Select_2.addItem("")
        self.Overlap_Select_2.addItem("")
        self.Overlap_Select_2.addItem("")
        self.Overlap_Select_2.addItem("")
        self.Overlap_Select_2.addItem("")
        self.verticalLayout_3.addWidget(self.Overlap_Select_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.view2_opacity = QtWidgets.QSlider(self.tab_2)
        self.view2_opacity.setMaximum(100)
        self.view2_opacity.setProperty("value", 80)
        self.view2_opacity.setOrientation(QtCore.Qt.Horizontal)
        self.view2_opacity.setObjectName("view2_opacity")
        self.horizontalLayout_8.addWidget(self.view2_opacity)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_4.addWidget(self.label_23)
        self.updatelist_2 = QtWidgets.QComboBox(self.tab_2)
        self.updatelist_2.setObjectName("updatelist_2")
        self.updatelist_2.addItem("")
        self.updatelist_2.addItem("")
        self.updatelist_2.addItem("")
        self.updatelist_2.addItem("")
        self.horizontalLayout_4.addWidget(self.updatelist_2)
        self.Generate_position_2 = QtWidgets.QPushButton(self.tab_2)
        self.Generate_position_2.setStyleSheet("QPushButton:checked {\n"
"    background-color:rgb(255, 0, 0)\n"
"}")
        self.Generate_position_2.setCheckable(True)
        self.Generate_position_2.setChecked(False)
        self.Generate_position_2.setObjectName("Generate_position_2")
        self.horizontalLayout_4.addWidget(self.Generate_position_2)
        self.ClearAll_2 = QtWidgets.QPushButton(self.tab_2)
        self.ClearAll_2.setObjectName("ClearAll_2")
        self.horizontalLayout_4.addWidget(self.ClearAll_2)
        self.EditPos_2 = QtWidgets.QPushButton(self.tab_2)
        self.EditPos_2.setCheckable(True)
        self.EditPos_2.setObjectName("EditPos_2")
        self.horizontalLayout_4.addWidget(self.EditPos_2)
        self.MovePos_2 = QtWidgets.QPushButton(self.tab_2)
        self.MovePos_2.setCheckable(True)
        self.MovePos_2.setObjectName("MovePos_2")
        self.horizontalLayout_4.addWidget(self.MovePos_2)
        self.horizontalLayout_4.setStretch(1, 10)
        self.horizontalLayout_4.setStretch(3, 10)
        self.horizontalLayout_4.setStretch(4, 10)
        self.horizontalLayout_4.setStretch(5, 10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.List_number_2 = QtWidgets.QSpinBox(self.tab_2)
        self.List_number_2.setMaximum(999)
        self.List_number_2.setProperty("value", 10)
        self.List_number_2.setObjectName("List_number_2")
        self.horizontalLayout_5.addWidget(self.List_number_2)
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_5.addWidget(self.label_20)
        self.Threshold_2 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.Threshold_2.setMinimum(-1.0)
        self.Threshold_2.setMaximum(9999.0)
        self.Threshold_2.setProperty("value", 1.0)
        self.Threshold_2.setObjectName("Threshold_2")
        self.horizontalLayout_5.addWidget(self.Threshold_2)
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_5.addWidget(self.label_21)
        self.Min_peak_distance_2 = QtWidgets.QSpinBox(self.tab_2)
        self.Min_peak_distance_2.setMaximum(999)
        self.Min_peak_distance_2.setProperty("value", 0)
        self.Min_peak_distance_2.setObjectName("Min_peak_distance_2")
        self.horizontalLayout_5.addWidget(self.Min_peak_distance_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.viwe2_move_up = QtWidgets.QPushButton(self.tab_2)
        self.viwe2_move_up.setObjectName("viwe2_move_up")
        self.gridLayout_11.addWidget(self.viwe2_move_up, 0, 1, 1, 1)
        self.viwe2_move_right = QtWidgets.QPushButton(self.tab_2)
        self.viwe2_move_right.setObjectName("viwe2_move_right")
        self.gridLayout_11.addWidget(self.viwe2_move_right, 1, 2, 1, 1)
        self.viwe2_move_left = QtWidgets.QPushButton(self.tab_2)
        self.viwe2_move_left.setObjectName("viwe2_move_left")
        self.gridLayout_11.addWidget(self.viwe2_move_left, 1, 0, 1, 1)
        self.viwe2_move_down = QtWidgets.QPushButton(self.tab_2)
        self.viwe2_move_down.setObjectName("viwe2_move_down")
        self.gridLayout_11.addWidget(self.viwe2_move_down, 2, 1, 1, 1)
        self.collectAllpos_2 = QtWidgets.QPushButton(self.tab_2)
        self.collectAllpos_2.setObjectName("collectAllpos_2")
        self.gridLayout_11.addWidget(self.collectAllpos_2, 3, 2, 1, 1)
        self.DetailInfo2 = QtWidgets.QPushButton(self.tab_2)
        self.DetailInfo2.setObjectName("DetailInfo2")
        self.gridLayout_11.addWidget(self.DetailInfo2, 3, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_11)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 1, 3, 3, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 2, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.hutchvideo1 = QtWidgets.QGraphicsView(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hutchvideo1.sizePolicy().hasHeightForWidth())
        self.hutchvideo1.setSizePolicy(sizePolicy)
        self.hutchvideo1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.hutchvideo1.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.hutchvideo1.setTransformationAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.hutchvideo1.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.hutchvideo1.setObjectName("hutchvideo1")
        self.verticalLayout_6.addWidget(self.hutchvideo1)
        self.hutchvideo1_scale = QtWidgets.QSlider(self.tab_2)
        self.hutchvideo1_scale.setMinimum(0)
        self.hutchvideo1_scale.setMaximum(100)
        self.hutchvideo1_scale.setOrientation(QtCore.Qt.Horizontal)
        self.hutchvideo1_scale.setObjectName("hutchvideo1_scale")
        self.verticalLayout_6.addWidget(self.hutchvideo1_scale)
        self.hutchvideo2 = QtWidgets.QGraphicsView(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hutchvideo2.sizePolicy().hasHeightForWidth())
        self.hutchvideo2.setSizePolicy(sizePolicy)
        self.hutchvideo2.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.hutchvideo2.setTransformationAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.hutchvideo2.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.hutchvideo2.setObjectName("hutchvideo2")
        self.verticalLayout_6.addWidget(self.hutchvideo2)
        self.hutchvideo2_scale = QtWidgets.QSlider(self.tab_2)
        self.hutchvideo2_scale.setMinimum(0)
        self.hutchvideo2_scale.setMaximum(100)
        self.hutchvideo2_scale.setOrientation(QtCore.Qt.Horizontal)
        self.hutchvideo2_scale.setObjectName("hutchvideo2_scale")
        self.verticalLayout_6.addWidget(self.hutchvideo2_scale)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout_6.addLayout(self.gridLayout_13)
        self.verticalLayout_6.setStretch(0, 100)
        self.verticalLayout_6.setStretch(2, 100)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 3, 0, 1, 1)
        self.gridLayout_5.setColumnStretch(2, 50)
        self.gridLayout_5.setColumnStretch(3, 50)
        self.tabWidget.addTab(self.tab_2, "")
        self.SpecialOption = QtWidgets.QWidget()
        self.SpecialOption.setObjectName("SpecialOption")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.SpecialOption)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_25 = QtWidgets.QLabel(self.SpecialOption)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 0, 0, 1, 1)
        self.Raster_scoring_way = QtWidgets.QComboBox(self.SpecialOption)
        self.Raster_scoring_way.setObjectName("Raster_scoring_way")
        self.Raster_scoring_way.addItem("")
        self.Raster_scoring_way.addItem("")
        self.gridLayout_6.addWidget(self.Raster_scoring_way, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 2, 0, 1, 1)
        self.PostCollecttionDelay = QtWidgets.QDoubleSpinBox(self.SpecialOption)
        self.PostCollecttionDelay.setDecimals(1)
        self.PostCollecttionDelay.setMaximum(1000.0)
        self.PostCollecttionDelay.setObjectName("PostCollecttionDelay")
        self.gridLayout_6.addWidget(self.PostCollecttionDelay, 1, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.SpecialOption)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 1, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.SpecialOption)
        self.label_28.setWordWrap(True)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 1, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.SpecialOption)
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 1, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.SpecialOption, "")
        self.SSXCollect = QtWidgets.QWidget()
        self.SSXCollect.setObjectName("SSXCollect")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.SSXCollect)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_32 = QtWidgets.QLabel(self.SSXCollect)
        self.label_32.setObjectName("label_32")
        self.gridLayout_14.addWidget(self.label_32, 3, 2, 1, 1)
        self.SSX_Totaltime = QtWidgets.QDoubleSpinBox(self.SSXCollect)
        self.SSX_Totaltime.setEnabled(False)
        self.SSX_Totaltime.setReadOnly(True)
        self.SSX_Totaltime.setMinimum(0.0)
        self.SSX_Totaltime.setMaximum(99999999999999.0)
        self.SSX_Totaltime.setProperty("value", 0.0)
        self.SSX_Totaltime.setObjectName("SSX_Totaltime")
        self.gridLayout_14.addWidget(self.SSX_Totaltime, 9, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.SSXCollect)
        self.label_5.setObjectName("label_5")
        self.gridLayout_14.addWidget(self.label_5, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem4, 24, 3, 1, 1)
        self.SSX_LassrTimeArray_2 = QtWidgets.QDoubleSpinBox(self.SSXCollect)
        self.SSX_LassrTimeArray_2.setDecimals(0)
        self.SSX_LassrTimeArray_2.setMinimum(0.0)
        self.SSX_LassrTimeArray_2.setMaximum(9999999999.0)
        self.SSX_LassrTimeArray_2.setProperty("value", 700.0)
        self.SSX_LassrTimeArray_2.setObjectName("SSX_LassrTimeArray_2")
        self.gridLayout_14.addWidget(self.SSX_LassrTimeArray_2, 12, 4, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.SSXCollect)
        self.label_47.setObjectName("label_47")
        self.gridLayout_14.addWidget(self.label_47, 16, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.SSXCollect)
        self.label_45.setObjectName("label_45")
        self.gridLayout_14.addWidget(self.label_45, 14, 0, 1, 1)
        self.SSX_PeakSearch_threshold = QtWidgets.QSpinBox(self.SSXCollect)
        self.SSX_PeakSearch_threshold.setMinimum(1)
        self.SSX_PeakSearch_threshold.setMaximum(65535)
        self.SSX_PeakSearch_threshold.setProperty("value", 800)
        self.SSX_PeakSearch_threshold.setObjectName("SSX_PeakSearch_threshold")
        self.gridLayout_14.addWidget(self.SSX_PeakSearch_threshold, 14, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.SSXCollect)
        self.label_43.setObjectName("label_43")
        self.gridLayout_14.addWidget(self.label_43, 12, 0, 1, 1)
        self.SSX_PeakSearch_minsnr = QtWidgets.QSpinBox(self.SSXCollect)
        self.SSX_PeakSearch_minsnr.setMinimum(1)
        self.SSX_PeakSearch_minsnr.setMaximum(65535)
        self.SSX_PeakSearch_minsnr.setProperty("value", 5)
        self.SSX_PeakSearch_minsnr.setObjectName("SSX_PeakSearch_minsnr")
        self.gridLayout_14.addWidget(self.SSX_PeakSearch_minsnr, 15, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.SSXCollect)
        self.label_35.setObjectName("label_35")
        self.gridLayout_14.addWidget(self.label_35, 6, 2, 1, 1)
        self.SSX_Distance = QtWidgets.QDoubleSpinBox(self.SSXCollect)
        self.SSX_Distance.setMinimum(140.0)
        self.SSX_Distance.setMaximum(900.0)
        self.SSX_Distance.setObjectName("SSX_Distance")
        self.gridLayout_14.addWidget(self.SSX_Distance, 3, 3, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.SSXCollect)
        self.label_33.setObjectName("label_33")
        self.gridLayout_14.addWidget(self.label_33, 4, 2, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.SSXCollect)
        self.label_39.setObjectName("label_39")
        self.gridLayout_14.addWidget(self.label_39, 9, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.SSXCollect)
        self.label_34.setObjectName("label_34")
        self.gridLayout_14.addWidget(self.label_34, 5, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.SSXCollect)
        self.label_31.setObjectName("label_31")
        self.gridLayout_14.addWidget(self.label_31, 2, 2, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.SSXCollect)
        self.label_52.setObjectName("label_52")
        self.gridLayout_14.addWidget(self.label_52, 21, 0, 1, 1)
        self.SSX_Resolution = QtWidgets.QDoubleSpinBox(self.SSXCollect)
        self.SSX_Resolution.setEnabled(True)
        self.SSX_Resolution.setReadOnly(True)
        self.SSX_Resolution.setObjectName("SSX_Resolution")
        self.gridLayout_14.addWidget(self.SSX_Resolution, 3, 5, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem5, 24, 0, 1, 1)
        self.SSX_Directory = QtWidgets.QLineEdit(self.SSXCollect)
        self.SSX_Directory.setObjectName("SSX_Directory")
        self.gridLayout_14.addWidget(self.SSX_Directory, 1, 3, 1, 3)
        self.SSX_DetectorMode = QtWidgets.QComboBox(self.SSXCollect)
        self.SSX_DetectorMode.setObjectName("SSX_DetectorMode")
        self.SSX_DetectorMode.addItem("")
        self.SSX_DetectorMode.addItem("")
        self.SSX_DetectorMode.addItem("")
        self.SSX_DetectorMode.addItem("")
        self.gridLayout_14.addWidget(self.SSX_DetectorMode, 2, 3, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.SSXCollect)
        self.label_50.setObjectName("label_50")
        self.gridLayout_14.addWidget(self.label_50, 19, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.SSXCollect)
        self.label_49.setObjectName("label_49")
        self.gridLayout_14.addWidget(self.label_49, 18, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.SSXCollect)
        self.label_53.setObjectName("label_53")
        self.gridLayout_14.addWidget(self.label_53, 22, 0, 1, 1)
        self.SSX_StartCollect = QtWidgets.QCommandLinkButton(self.SSXCollect)
        self.SSX_StartCollect.setObjectName("SSX_StartCollect")
        self.gridLayout_14.addWidget(self.SSX_StartCollect, 1, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.SSXCollect)
        self.label_51.setObjectName("label_51")
        self.gridLayout_14.addWidget(self.label_51, 20, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.SSXCollect)
        self.label_42.setObjectName("label_42")
        self.gridLayout_14.addWidget(self.label_42, 12, 2, 1, 1)
        self.SSX_PeakSearchAlgorithm = QtWidgets.QComboBox(self.SSXCollect)
        self.SSX_PeakSearchAlgorithm.setObjectName("SSX_PeakSearchAlgorithm")
        self.SSX_PeakSearchAlgorithm.addItem("")
        self.SSX_PeakSearchAlgorithm.addItem("")
        self.gridLayout_14.addWidget(self.SSX_PeakSearchAlgorithm, 13, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.SSXCollect)
        self.label_30.setObjectName("label_30")
        self.gridLayout_14.addWidget(self.label_30, 1, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.SSXCollect)
        self.label_36.setObjectName("label_36")
        self.gridLayout_14.addWidget(self.label_36, 7, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem6, 0, 0, 1, 2)
        self.label_38 = QtWidgets.QLabel(self.SSXCollect)
        self.label_38.setObjectName("label_38")
        self.gridLayout_14.addWidget(self.label_38, 8, 2, 1, 1)
        self.SSX_NumberFrames = QtWidgets.QSpinBox(self.SSXCollect)
        self.SSX_NumberFrames.setMinimum(0)
        self.SSX_NumberFrames.setMaximum(10800000)
        self.SSX_NumberFrames.setSingleStep(1000)
        self.SSX_NumberFrames.setProperty("value", 0)
        self.SSX_NumberFrames.setObjectName("SSX_NumberFrames")
        self.gridLayout_14.addWidget(self.SSX_NumberFrames, 8, 3, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.SSXCollect)
        self.label_37.setObjectName("label_37")
        self.gridLayout_14.addWidget(self.label_37, 3, 4, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.SSXCollect)
        self.label_41.setObjectName("label_41")
        self.gridLayout_14.addWidget(self.label_41, 11, 2, 1, 1)
        self.SSX_Attenuation = QtWidgets.QDoubleSpinBox(self.SSXCollect)
        self.SSX_Attenuation.setMaximum(100.0)
        self.SSX_Attenuation.setObjectName("SSX_Attenuation")
        self.gridLayout_14.addWidget(self.SSX_Attenuation, 6, 3, 1, 1)
        self.SSX_LaserInitialState = QtWidgets.QComboBox(self.SSXCollect)
        self.SSX_LaserInitialState.setEditable(False)
        self.SSX_LaserInitialState.setObjectName("SSX_LaserInitialState")
        self.SSX_LaserInitialState.addItem("")
        self.SSX_LaserInitialState.addItem("")
        self.gridLayout_14.addWidget(self.SSX_LaserInitialState, 11, 3, 1, 1)
        self.SSX_Time = QtWidgets.QDoubleSpinBox(self.SSXCollect)
        self.SSX_Time.setMinimum(2.0)
        self.SSX_Time.setMaximum(10000000.0)
        self.SSX_Time.setProperty("value", 8.0)
        self.SSX_Time.setObjectName("SSX_Time")
        self.gridLayout_14.addWidget(self.SSX_Time, 7, 3, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.SSXCollect)
        self.label_48.setObjectName("label_48")
        self.gridLayout_14.addWidget(self.label_48, 17, 0, 1, 1)
        self.SSX_LassrTimeArray_1 = QtWidgets.QDoubleSpinBox(self.SSXCollect)
        self.SSX_LassrTimeArray_1.setDecimals(0)
        self.SSX_LassrTimeArray_1.setMinimum(0.0)
        self.SSX_LassrTimeArray_1.setMaximum(9999999999.0)
        self.SSX_LassrTimeArray_1.setProperty("value", 300.0)
        self.SSX_LassrTimeArray_1.setObjectName("SSX_LassrTimeArray_1")
        self.gridLayout_14.addWidget(self.SSX_LassrTimeArray_1, 12, 3, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.SSXCollect)
        self.label_46.setObjectName("label_46")
        self.gridLayout_14.addWidget(self.label_46, 15, 0, 1, 1)
        self.SSX_Prefix = QtWidgets.QLineEdit(self.SSXCollect)
        self.SSX_Prefix.setObjectName("SSX_Prefix")
        self.gridLayout_14.addWidget(self.SSX_Prefix, 0, 3, 1, 3)
        self.sda = QtWidgets.QLabel(self.SSXCollect)
        self.sda.setObjectName("sda")
        self.gridLayout_14.addWidget(self.sda, 13, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.SSXCollect)
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.gridLayout_14.addWidget(self.label_40, 10, 2, 1, 1)
        self.SSX_StopCollect = QtWidgets.QCommandLinkButton(self.SSXCollect)
        self.SSX_StopCollect.setObjectName("SSX_StopCollect")
        self.gridLayout_14.addWidget(self.SSX_StopCollect, 2, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.SSXCollect)
        self.label_54.setObjectName("label_54")
        self.gridLayout_14.addWidget(self.label_54, 23, 0, 1, 1)
        self.SSX_PeakSearch_min_pix_count = QtWidgets.QSpinBox(self.SSXCollect)
        self.SSX_PeakSearch_min_pix_count.setMinimum(1)
        self.SSX_PeakSearch_min_pix_count.setMaximum(65535)
        self.SSX_PeakSearch_min_pix_count.setProperty("value", 5)
        self.SSX_PeakSearch_min_pix_count.setObjectName("SSX_PeakSearch_min_pix_count")
        self.gridLayout_14.addWidget(self.SSX_PeakSearch_min_pix_count, 16, 1, 1, 1)
        self.SSX_PeakSearch_max_pix_count = QtWidgets.QSpinBox(self.SSXCollect)
        self.SSX_PeakSearch_max_pix_count.setMinimum(1)
        self.SSX_PeakSearch_max_pix_count.setMaximum(65535)
        self.SSX_PeakSearch_max_pix_count.setProperty("value", 5)
        self.SSX_PeakSearch_max_pix_count.setObjectName("SSX_PeakSearch_max_pix_count")
        self.gridLayout_14.addWidget(self.SSX_PeakSearch_max_pix_count, 17, 1, 1, 1)
        self.SSX_PeakSearch_local_bg_radius = QtWidgets.QSpinBox(self.SSXCollect)
        self.SSX_PeakSearch_local_bg_radius.setMinimum(1)
        self.SSX_PeakSearch_local_bg_radius.setMaximum(65535)
        self.SSX_PeakSearch_local_bg_radius.setProperty("value", 5)
        self.SSX_PeakSearch_local_bg_radius.setObjectName("SSX_PeakSearch_local_bg_radius")
        self.gridLayout_14.addWidget(self.SSX_PeakSearch_local_bg_radius, 18, 1, 1, 1)
        self.SSX_PeakSearch_min_res = QtWidgets.QSpinBox(self.SSXCollect)
        self.SSX_PeakSearch_min_res.setMinimum(1)
        self.SSX_PeakSearch_min_res.setMaximum(65535)
        self.SSX_PeakSearch_min_res.setProperty("value", 5)
        self.SSX_PeakSearch_min_res.setObjectName("SSX_PeakSearch_min_res")
        self.gridLayout_14.addWidget(self.SSX_PeakSearch_min_res, 19, 1, 1, 1)
        self.SSX_PeakSearch_max_res = QtWidgets.QSpinBox(self.SSXCollect)
        self.SSX_PeakSearch_max_res.setMinimum(1)
        self.SSX_PeakSearch_max_res.setMaximum(65535)
        self.SSX_PeakSearch_max_res.setProperty("value", 5)
        self.SSX_PeakSearch_max_res.setObjectName("SSX_PeakSearch_max_res")
        self.gridLayout_14.addWidget(self.SSX_PeakSearch_max_res, 20, 1, 1, 1)
        self.SSX_PeakSearch_min_snr_biggest_pix = QtWidgets.QSpinBox(self.SSXCollect)
        self.SSX_PeakSearch_min_snr_biggest_pix.setMinimum(1)
        self.SSX_PeakSearch_min_snr_biggest_pix.setMaximum(65535)
        self.SSX_PeakSearch_min_snr_biggest_pix.setProperty("value", 5)
        self.SSX_PeakSearch_min_snr_biggest_pix.setObjectName("SSX_PeakSearch_min_snr_biggest_pix")
        self.gridLayout_14.addWidget(self.SSX_PeakSearch_min_snr_biggest_pix, 21, 1, 1, 1)
        self.SSX_PeakSearch_min_snr_peak_pix = QtWidgets.QSpinBox(self.SSXCollect)
        self.SSX_PeakSearch_min_snr_peak_pix.setMinimum(1)
        self.SSX_PeakSearch_min_snr_peak_pix.setMaximum(65535)
        self.SSX_PeakSearch_min_snr_peak_pix.setProperty("value", 5)
        self.SSX_PeakSearch_min_snr_peak_pix.setObjectName("SSX_PeakSearch_min_snr_peak_pix")
        self.gridLayout_14.addWidget(self.SSX_PeakSearch_min_snr_peak_pix, 22, 1, 1, 1)
        self.SSX_PeakSearch_min_sig = QtWidgets.QSpinBox(self.SSXCollect)
        self.SSX_PeakSearch_min_sig.setMinimum(1)
        self.SSX_PeakSearch_min_sig.setMaximum(65535)
        self.SSX_PeakSearch_min_sig.setProperty("value", 5)
        self.SSX_PeakSearch_min_sig.setObjectName("SSX_PeakSearch_min_sig")
        self.gridLayout_14.addWidget(self.SSX_PeakSearch_min_sig, 23, 1, 1, 1)
        self.SSX_LaserInitialState_2 = QtWidgets.QComboBox(self.SSXCollect)
        self.SSX_LaserInitialState_2.setEnabled(False)
        self.SSX_LaserInitialState_2.setObjectName("SSX_LaserInitialState_2")
        self.SSX_LaserInitialState_2.addItem("")
        self.SSX_LaserInitialState_2.addItem("")
        self.gridLayout_14.addWidget(self.SSX_LaserInitialState_2, 11, 4, 1, 1)
        self.SSX_Fileindex = QtWidgets.QSpinBox(self.SSXCollect)
        self.SSX_Fileindex.setEnabled(False)
        self.SSX_Fileindex.setMaximum(1000)
        self.SSX_Fileindex.setObjectName("SSX_Fileindex")
        self.gridLayout_14.addWidget(self.SSX_Fileindex, 2, 5, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.SSXCollect)
        self.label_44.setObjectName("label_44")
        self.gridLayout_14.addWidget(self.label_44, 2, 4, 1, 1)
        self.SSX_CurrentFrame = QtWidgets.QSpinBox(self.SSXCollect)
        self.SSX_CurrentFrame.setEnabled(False)
        self.SSX_CurrentFrame.setMinimum(0)
        self.SSX_CurrentFrame.setMaximum(10800000)
        self.SSX_CurrentFrame.setSingleStep(1000)
        self.SSX_CurrentFrame.setProperty("value", 0)
        self.SSX_CurrentFrame.setObjectName("SSX_CurrentFrame")
        self.gridLayout_14.addWidget(self.SSX_CurrentFrame, 8, 4, 1, 1)
        self.SSXAutoRepeat = QtWidgets.QCheckBox(self.SSXCollect)
        self.SSXAutoRepeat.setObjectName("SSXAutoRepeat")
        self.gridLayout_14.addWidget(self.SSXAutoRepeat, 1, 1, 1, 1)
        self.tabWidget.addTab(self.SSXCollect, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.debug_operation = QtWidgets.QPushButton(self.tab)
        self.debug_operation.setObjectName("debug_operation")
        self.gridLayout_8.addWidget(self.debug_operation, 1, 0, 1, 1)
        self.debug_raster = QtWidgets.QPushButton(self.tab)
        self.debug_raster.setObjectName("debug_raster")
        self.gridLayout_8.addWidget(self.debug_raster, 2, 0, 1, 1)
        self.debug_string = QtWidgets.QPushButton(self.tab)
        self.debug_string.setObjectName("debug_string")
        self.gridLayout_8.addWidget(self.debug_string, 0, 1, 1, 1)
        self.debug_motor = QtWidgets.QPushButton(self.tab)
        self.debug_motor.setObjectName("debug_motor")
        self.gridLayout_8.addWidget(self.debug_motor, 0, 0, 1, 1)
        self.debug_shutter = QtWidgets.QPushButton(self.tab)
        self.debug_shutter.setObjectName("debug_shutter")
        self.gridLayout_8.addWidget(self.debug_shutter, 1, 1, 1, 1)
        self.debug_Debug = QtWidgets.QPushButton(self.tab)
        self.debug_Debug.setObjectName("debug_Debug")
        self.gridLayout_8.addWidget(self.debug_Debug, 2, 1, 1, 1)
        self.debug_loaddata = QtWidgets.QPushButton(self.tab)
        self.debug_loaddata.setObjectName("debug_loaddata")
        self.gridLayout_8.addWidget(self.debug_loaddata, 3, 0, 1, 1)
        self.RecollectRaster = QtWidgets.QPushButton(self.tab)
        self.RecollectRaster.setObjectName("RecollectRaster")
        self.gridLayout_8.addWidget(self.RecollectRaster, 3, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1864, 20))
        self.menubar.setObjectName("menubar")
        self.menuMeshBestGUI = QtWidgets.QMenu(self.menubar)
        self.menuMeshBestGUI.setObjectName("menuMeshBestGUI")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuMeshBestGUI.addSeparator()
        self.menubar.addAction(self.menuMeshBestGUI.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(1)
        self.selectGridsize.setCurrentIndex(8)
        self.selectBeamsize.setCurrentIndex(10)
        self.selectROI.setCurrentIndex(0)
        self.select2scan.setCurrentIndex(0)
        self.Overlap_Select_1.setCurrentIndex(1)
        self.Overlap_Select_2.setCurrentIndex(1)
        self.SSX_PeakSearchAlgorithm.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mesh and Collect"))
        self.LastInfo.setText(_translate("MainWindow", "LastInfo"))
        self.label.setText(_translate("MainWindow", "TPS State:"))
        self.TPSStateText.setText(_translate("MainWindow", "Open"))
        self.Current.setSuffix(_translate("MainWindow", " mA"))
        self.label_2.setText(_translate("MainWindow", "Energy:"))
        self.Energy.setSuffix(_translate("MainWindow", " ev"))
        self.label_6.setText(_translate("MainWindow", "Beamline flux:"))
        self.beamlineflux.setText(_translate("MainWindow", "0 phs/sec"))
        self.label_24.setText(_translate("MainWindow", "Time to Injection:"))
        self.timetoinj.setText(_translate("MainWindow", "-1 sec"))
        self.Abort.setText(_translate("MainWindow", "Abort"))
        self.Active.setText(_translate("MainWindow", "Unknow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "I has no idea....."))
        self.comboBox.setItemText(1, _translate("MainWindow", "Single Crystal"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Small wedge"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Project Setup"))
        self.Focus_pos_s.setText(_translate("MainWindow", ">"))
        self.StartRaster.setText(_translate("MainWindow", "Start Raster"))
        self.Focus_neg_l.setText(_translate("MainWindow", "<<"))
        self.Focus_pos_l.setText(_translate("MainWindow", ">>"))
        self.Direct_collect.setText(_translate("MainWindow", "Direct Fixed Target Data Collect"))
        self.Raster.setText(_translate("MainWindow", "Take Raster Image"))
        self.Autocenter.setText(_translate("MainWindow", "Auto Center"))
        self.Zoom1.setText(_translate("MainWindow", "Zoom1"))
        self.pos_10deg.setText(_translate("MainWindow", "+10deg"))
        self.pos_90deg.setText(_translate("MainWindow", "+90deg"))
        self.Centermode.setText(_translate("MainWindow", "Center mode"))
        self.Zoom2.setText(_translate("MainWindow", "Zoom2"))
        self.neg_90deg.setText(_translate("MainWindow", "-90deg"))
        self.Zoom3.setText(_translate("MainWindow", "Zoom3"))
        self.Zoom4.setText(_translate("MainWindow", "Zoom4"))
        self.Transfermode.setText(_translate("MainWindow", "Transfer mode"))
        self.label_7.setText(_translate("MainWindow", "Focus Centering"))
        self.Focus_neg_s.setText(_translate("MainWindow", "<"))
        self.neg_10deg.setText(_translate("MainWindow", "-10deg"))
        self.neg_5deg.setText(_translate("MainWindow", "-5deg"))
        self.neg_1deg.setText(_translate("MainWindow", "-1deg"))
        self.pos_1deg.setText(_translate("MainWindow", "+1deg"))
        self.pos_5deg.setText(_translate("MainWindow", "+5deg"))
        self.GetDefalutFolder.setText(_translate("MainWindow", "Defalut"))
        self.UpdateFolder.setText(_translate("MainWindow", "Update"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "File Setup"))
        self.label_16.setText(_translate("MainWindow", "Rotation"))
        self.label_14.setText(_translate("MainWindow", "Detector Distance"))
        self.ExpousetimeType.setItemText(0, _translate("MainWindow", "Exposure time"))
        self.ExpousetimeType.setItemText(1, _translate("MainWindow", "Rate"))
        self.rasterdose.setSuffix(_translate("MainWindow", "Mgy"))
        self.label_15.setText(_translate("MainWindow", "Dose"))
        self.label_13.setText(_translate("MainWindow", "Attenuation"))
        self.selectGridsize.setCurrentText(_translate("MainWindow", "20"))
        self.selectGridsize.setItemText(0, _translate("MainWindow", "100"))
        self.selectGridsize.setItemText(1, _translate("MainWindow", "90"))
        self.selectGridsize.setItemText(2, _translate("MainWindow", "80"))
        self.selectGridsize.setItemText(3, _translate("MainWindow", "70"))
        self.selectGridsize.setItemText(4, _translate("MainWindow", "60"))
        self.selectGridsize.setItemText(5, _translate("MainWindow", "50"))
        self.selectGridsize.setItemText(6, _translate("MainWindow", "40"))
        self.selectGridsize.setItemText(7, _translate("MainWindow", "30"))
        self.selectGridsize.setItemText(8, _translate("MainWindow", "20"))
        self.selectGridsize.setItemText(9, _translate("MainWindow", "10"))
        self.selectGridsize.setItemText(10, _translate("MainWindow", "5"))
        self.label_12.setText(_translate("MainWindow", "GirdSize"))
        self.selectBeamsize.setCurrentText(_translate("MainWindow", "5"))
        self.selectBeamsize.setItemText(0, _translate("MainWindow", "100"))
        self.selectBeamsize.setItemText(1, _translate("MainWindow", "90"))
        self.selectBeamsize.setItemText(2, _translate("MainWindow", "80"))
        self.selectBeamsize.setItemText(3, _translate("MainWindow", "70"))
        self.selectBeamsize.setItemText(4, _translate("MainWindow", "60"))
        self.selectBeamsize.setItemText(5, _translate("MainWindow", "50"))
        self.selectBeamsize.setItemText(6, _translate("MainWindow", "40"))
        self.selectBeamsize.setItemText(7, _translate("MainWindow", "30"))
        self.selectBeamsize.setItemText(8, _translate("MainWindow", "20"))
        self.selectBeamsize.setItemText(9, _translate("MainWindow", "10"))
        self.selectBeamsize.setItemText(10, _translate("MainWindow", "5"))
        self.selectBeamsize.setItemText(11, _translate("MainWindow", "1"))
        self.selectROI.setCurrentText(_translate("MainWindow", "Enable"))
        self.selectROI.setItemText(0, _translate("MainWindow", "Enable"))
        self.selectROI.setItemText(1, _translate("MainWindow", "Disable"))
        self.label_17.setText(_translate("MainWindow", "Beamsize"))
        self.label_18.setText(_translate("MainWindow", "ROI"))
        self.label_26.setText(_translate("MainWindow", "Scan 2 view"))
        self.select2scan.setCurrentText(_translate("MainWindow", "Enable"))
        self.select2scan.setItemText(0, _translate("MainWindow", "Enable"))
        self.select2scan.setItemText(1, _translate("MainWindow", "Disable"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "Raster scan Par"))
        self.Overlap_Select_1.setItemText(0, _translate("MainWindow", "None"))
        self.Overlap_Select_1.setItemText(1, _translate("MainWindow", "Grid"))
        self.Overlap_Select_1.setItemText(2, _translate("MainWindow", "Dozor score"))
        self.Overlap_Select_1.setItemText(3, _translate("MainWindow", "Number of Peaks"))
        self.Overlap_Select_1.setItemText(4, _translate("MainWindow", "Visible resolution"))
        self.Overlap_Select_1.setItemText(5, _translate("MainWindow", "Crystal Map"))
        self.Overlap_Select_1.setItemText(6, _translate("MainWindow", "Crystal Map with Dozor score"))
        self.label_8.setText(_translate("MainWindow", "Opacity(%)"))
        self.label_22.setText(_translate("MainWindow", "Position pick"))
        self.updatelist_1.setItemText(0, _translate("MainWindow", "Meshbest"))
        self.updatelist_1.setItemText(1, _translate("MainWindow", "Manual"))
        self.updatelist_1.setItemText(2, _translate("MainWindow", "base on peak number"))
        self.updatelist_1.setItemText(3, _translate("MainWindow", "Crystal position from OM image"))
        self.Generate_position_1.setText(_translate("MainWindow", "Generate"))
        self.ClearAll_1.setText(_translate("MainWindow", "Clear All"))
        self.EditPos_1.setText(_translate("MainWindow", "Add/Del Pos."))
        self.MovePos_1.setText(_translate("MainWindow", "Move Pos."))
        self.label_4.setText(_translate("MainWindow", "MaxNumber"))
        self.label_11.setText(_translate("MainWindow", "Threshold"))
        self.label_19.setText(_translate("MainWindow", "Min distance between peak"))
        self.viwe1_move_down.setText(_translate("MainWindow", "v"))
        self.viwe1_move_up.setText(_translate("MainWindow", "^"))
        self.viwe1_move_right.setText(_translate("MainWindow", ">"))
        self.collectAllpos_1.setText(_translate("MainWindow", "Collect All Position"))
        self.DetailInfo1.setText(_translate("MainWindow", "Display collect info"))
        self.viwe1_move_left.setText(_translate("MainWindow", "<"))
        self.Overlap_Select_2.setItemText(0, _translate("MainWindow", "None"))
        self.Overlap_Select_2.setItemText(1, _translate("MainWindow", "Grid"))
        self.Overlap_Select_2.setItemText(2, _translate("MainWindow", "Dozor score"))
        self.Overlap_Select_2.setItemText(3, _translate("MainWindow", "Number of Peaks"))
        self.Overlap_Select_2.setItemText(4, _translate("MainWindow", "Visible resolution"))
        self.Overlap_Select_2.setItemText(5, _translate("MainWindow", "Crystal Map"))
        self.Overlap_Select_2.setItemText(6, _translate("MainWindow", "Crystal Map with Dozor score"))
        self.label_9.setText(_translate("MainWindow", "Opacity(%)"))
        self.label_23.setText(_translate("MainWindow", "Position pick"))
        self.updatelist_2.setItemText(0, _translate("MainWindow", "Meshbest"))
        self.updatelist_2.setItemText(1, _translate("MainWindow", "Manual"))
        self.updatelist_2.setItemText(2, _translate("MainWindow", "base on peak number"))
        self.updatelist_2.setItemText(3, _translate("MainWindow", "Crystal position from OM image"))
        self.Generate_position_2.setText(_translate("MainWindow", "Generate"))
        self.ClearAll_2.setText(_translate("MainWindow", "Clear All"))
        self.EditPos_2.setText(_translate("MainWindow", "Add/Del Pos."))
        self.MovePos_2.setText(_translate("MainWindow", "Move Pos."))
        self.label_10.setText(_translate("MainWindow", "MaxNumber"))
        self.label_20.setText(_translate("MainWindow", "Threshold"))
        self.label_21.setText(_translate("MainWindow", "Min distance between peak"))
        self.viwe2_move_up.setText(_translate("MainWindow", "^"))
        self.viwe2_move_right.setText(_translate("MainWindow", ">"))
        self.viwe2_move_left.setText(_translate("MainWindow", "<"))
        self.viwe2_move_down.setText(_translate("MainWindow", "v"))
        self.collectAllpos_2.setText(_translate("MainWindow", "Collect All Position"))
        self.DetailInfo2.setText(_translate("MainWindow", "Display collect info"))
        self.label_3.setText(_translate("MainWindow", "Hutch video"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Crystal Center and Raster"))
        self.label_25.setText(_translate("MainWindow", "Raster scan scoring"))
        self.Raster_scoring_way.setItemText(0, _translate("MainWindow", "Dozor"))
        self.Raster_scoring_way.setItemText(1, _translate("MainWindow", "None"))
        self.PostCollecttionDelay.setSuffix(_translate("MainWindow", "sec"))
        self.label_27.setText(_translate("MainWindow", "Post collection delay"))
        self.label_28.setText(_translate("MainWindow", "Adds an intentional pause between consecutive small-wedge data collections. After one dataset (wedge) finishes and before the next dataset begins, the system waits for the specified duration.Use this delay to:allow the crystal to relax back toward its ground state"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SpecialOption), _translate("MainWindow", "Special Option"))
        self.label_32.setText(_translate("MainWindow", "Distance"))
        self.SSX_Totaltime.setSuffix(_translate("MainWindow", "sec"))
        self.label_5.setText(_translate("MainWindow", "Prefix"))
        self.SSX_LassrTimeArray_2.setSuffix(_translate("MainWindow", "ms"))
        self.label_47.setText(_translate("MainWindow", "min-pix-count"))
        self.label_45.setText(_translate("MainWindow", "Peak threshold"))
        self.label_43.setText(_translate("MainWindow", "On-line peak search par"))
        self.label_35.setText(_translate("MainWindow", "Attenuation"))
        self.SSX_Distance.setSuffix(_translate("MainWindow", "mm"))
        self.label_33.setText(_translate("MainWindow", "Beam size"))
        self.label_39.setText(_translate("MainWindow", "Total Collection time"))
        self.label_34.setText(_translate("MainWindow", "Beam stop"))
        self.label_31.setText(_translate("MainWindow", "Detector mode"))
        self.label_52.setText(_translate("MainWindow", "min-snr-biggest-pix"))
        self.SSX_Resolution.setSuffix(_translate("MainWindow", "A"))
        self.SSX_DetectorMode.setItemText(0, _translate("MainWindow", "Normal (16M)"))
        self.SSX_DetectorMode.setItemText(1, _translate("MainWindow", "ROI (9M)"))
        self.SSX_DetectorMode.setItemText(2, _translate("MainWindow", "High frame rate in 16M"))
        self.SSX_DetectorMode.setItemText(3, _translate("MainWindow", "High frame rate in ROI"))
        self.label_50.setText(_translate("MainWindow", "min-res"))
        self.label_49.setText(_translate("MainWindow", "local-bg-radius"))
        self.label_53.setText(_translate("MainWindow", "min-snr-peak-pix"))
        self.SSX_StartCollect.setText(_translate("MainWindow", "Collect"))
        self.label_51.setText(_translate("MainWindow", "max-res"))
        self.label_42.setText(_translate("MainWindow", "Laser Trigger Time array"))
        self.SSX_PeakSearchAlgorithm.setItemText(0, _translate("MainWindow", "peakfinder8"))
        self.SSX_PeakSearchAlgorithm.setItemText(1, _translate("MainWindow", "peakfinder9"))
        self.label_30.setText(_translate("MainWindow", "Directory"))
        self.label_36.setText(_translate("MainWindow", "Time for single frame"))
        self.label_38.setText(_translate("MainWindow", "Number frames"))
        self.label_37.setText(_translate("MainWindow", "Resolution"))
        self.label_41.setText(_translate("MainWindow", "Laser Trigger Initial State"))
        self.SSX_Attenuation.setSuffix(_translate("MainWindow", "%"))
        self.SSX_LaserInitialState.setItemText(0, _translate("MainWindow", "OFF"))
        self.SSX_LaserInitialState.setItemText(1, _translate("MainWindow", "ON"))
        self.SSX_Time.setSuffix(_translate("MainWindow", "ms"))
        self.label_48.setText(_translate("MainWindow", "max-pix-count"))
        self.SSX_LassrTimeArray_1.setSuffix(_translate("MainWindow", "ms"))
        self.label_46.setText(_translate("MainWindow", "min-snr"))
        self.sda.setText(_translate("MainWindow", "Peak search algorithm"))
        self.SSX_StopCollect.setText(_translate("MainWindow", "Stop"))
        self.label_54.setText(_translate("MainWindow", "min-sig"))
        self.SSX_LaserInitialState_2.setItemText(0, _translate("MainWindow", "OFF"))
        self.SSX_LaserInitialState_2.setItemText(1, _translate("MainWindow", "ON"))
        self.label_44.setText(_translate("MainWindow", "File index"))
        self.SSXAutoRepeat.setToolTip(_translate("MainWindow", "<html><head/><body><p>When enabled, a new collection will start automatically after the current data download is complete.</p></body></html>"))
        self.SSXAutoRepeat.setText(_translate("MainWindow", "Auto-Repeat"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SSXCollect), _translate("MainWindow", "SSX Collect"))
        self.debug_operation.setText(_translate("MainWindow", "operation"))
        self.debug_raster.setText(_translate("MainWindow", "Raster"))
        self.debug_string.setText(_translate("MainWindow", "string"))
        self.debug_motor.setText(_translate("MainWindow", "Motor"))
        self.debug_shutter.setText(_translate("MainWindow", "shutter"))
        self.debug_Debug.setText(_translate("MainWindow", "Debug"))
        self.debug_loaddata.setText(_translate("MainWindow", "Load data"))
        self.RecollectRaster.setText(_translate("MainWindow", "RecollectRaster"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Debug"))
        self.menuMeshBestGUI.setTitle(_translate("MainWindow", "Experiment"))

