# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TPS07A_meshbestGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1654, 1076)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LastInfo = QtWidgets.QLabel(self.centralwidget)
        self.LastInfo.setMinimumSize(QtCore.QSize(300, 0))
        self.LastInfo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LastInfo.setTextFormat(QtCore.Qt.AutoText)
        self.LastInfo.setObjectName("LastInfo")
        self.horizontalLayout.addWidget(self.LastInfo)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.TPSStateText = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.TPSStateText.setFont(font)
        self.TPSStateText.setObjectName("TPSStateText")
        self.horizontalLayout.addWidget(self.TPSStateText)
        self.Current = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.Current.setMinimumSize(QtCore.QSize(0, 0))
        self.Current.setAutoFillBackground(False)
        self.Current.setFrame(True)
        self.Current.setAlignment(QtCore.Qt.AlignCenter)
        self.Current.setReadOnly(True)
        self.Current.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Current.setSpecialValueText("")
        self.Current.setAccelerated(False)
        self.Current.setKeyboardTracking(True)
        self.Current.setPrefix("")
        self.Current.setDecimals(3)
        self.Current.setMaximum(1000.0)
        self.Current.setProperty("value", 500.0)
        self.Current.setObjectName("Current")
        self.horizontalLayout.addWidget(self.Current)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.Energy = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.Energy.setAlignment(QtCore.Qt.AlignCenter)
        self.Energy.setReadOnly(True)
        self.Energy.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Energy.setPrefix("")
        self.Energy.setDecimals(3)
        self.Energy.setMinimum(4000.0)
        self.Energy.setMaximum(20000.0)
        self.Energy.setObjectName("Energy")
        self.horizontalLayout.addWidget(self.Energy)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.beamlineflux = QtWidgets.QLabel(self.centralwidget)
        self.beamlineflux.setInputMethodHints(QtCore.Qt.ImhNone)
        self.beamlineflux.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.beamlineflux.setFrameShadow(QtWidgets.QFrame.Plain)
        self.beamlineflux.setLineWidth(1)
        self.beamlineflux.setMidLineWidth(0)
        self.beamlineflux.setTextFormat(QtCore.Qt.AutoText)
        self.beamlineflux.setScaledContents(False)
        self.beamlineflux.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.beamlineflux.setObjectName("beamlineflux")
        self.horizontalLayout.addWidget(self.beamlineflux)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout.addWidget(self.label_24)
        self.timetoinj = QtWidgets.QLabel(self.centralwidget)
        self.timetoinj.setInputMethodHints(QtCore.Qt.ImhNone)
        self.timetoinj.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.timetoinj.setFrameShadow(QtWidgets.QFrame.Plain)
        self.timetoinj.setLineWidth(1)
        self.timetoinj.setMidLineWidth(0)
        self.timetoinj.setTextFormat(QtCore.Qt.AutoText)
        self.timetoinj.setScaledContents(False)
        self.timetoinj.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.timetoinj.setObjectName("timetoinj")
        self.horizontalLayout.addWidget(self.timetoinj)
        self.Abort = QtWidgets.QPushButton(self.centralwidget)
        self.Abort.setStyleSheet("background:rgb(250, 0, 0)")
        self.Abort.setObjectName("Abort")
        self.horizontalLayout.addWidget(self.Abort)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Active = QtWidgets.QPushButton(self.centralwidget)
        self.Active.setMinimumSize(QtCore.QSize(140, 30))
        self.Active.setCheckable(True)
        self.Active.setChecked(False)
        self.Active.setAutoRepeat(False)
        self.Active.setAutoExclusive(False)
        self.Active.setAutoDefault(False)
        self.Active.setDefault(True)
        self.Active.setObjectName("Active")
        self.horizontalLayout.addWidget(self.Active)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 3)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.tab_1)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Autocenter = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Autocenter.sizePolicy().hasHeightForWidth())
        self.Autocenter.setSizePolicy(sizePolicy)
        self.Autocenter.setObjectName("Autocenter")
        self.gridLayout_4.addWidget(self.Autocenter, 14, 0, 1, 1)
        self.Zoom1 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Zoom1.sizePolicy().hasHeightForWidth())
        self.Zoom1.setSizePolicy(sizePolicy)
        self.Zoom1.setObjectName("Zoom1")
        self.gridLayout_4.addWidget(self.Zoom1, 9, 0, 1, 1)
        self.pos_10deg = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos_10deg.sizePolicy().hasHeightForWidth())
        self.pos_10deg.setSizePolicy(sizePolicy)
        self.pos_10deg.setObjectName("pos_10deg")
        self.gridLayout_4.addWidget(self.pos_10deg, 10, 2, 1, 1)
        self.pos_90deg = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos_90deg.sizePolicy().hasHeightForWidth())
        self.pos_90deg.setSizePolicy(sizePolicy)
        self.pos_90deg.setObjectName("pos_90deg")
        self.gridLayout_4.addWidget(self.pos_90deg, 10, 3, 1, 1)
        self.Centermode = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Centermode.sizePolicy().hasHeightForWidth())
        self.Centermode.setSizePolicy(sizePolicy)
        self.Centermode.setObjectName("Centermode")
        self.gridLayout_4.addWidget(self.Centermode, 14, 2, 1, 1)
        self.Zoom2 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Zoom2.sizePolicy().hasHeightForWidth())
        self.Zoom2.setSizePolicy(sizePolicy)
        self.Zoom2.setObjectName("Zoom2")
        self.gridLayout_4.addWidget(self.Zoom2, 9, 1, 1, 1)
        self.neg_90deg = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.neg_90deg.sizePolicy().hasHeightForWidth())
        self.neg_90deg.setSizePolicy(sizePolicy)
        self.neg_90deg.setObjectName("neg_90deg")
        self.gridLayout_4.addWidget(self.neg_90deg, 10, 0, 1, 1)
        self.neg_10deg = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.neg_10deg.sizePolicy().hasHeightForWidth())
        self.neg_10deg.setSizePolicy(sizePolicy)
        self.neg_10deg.setObjectName("neg_10deg")
        self.gridLayout_4.addWidget(self.neg_10deg, 10, 1, 1, 1)
        self.Zoom3 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Zoom3.sizePolicy().hasHeightForWidth())
        self.Zoom3.setSizePolicy(sizePolicy)
        self.Zoom3.setObjectName("Zoom3")
        self.gridLayout_4.addWidget(self.Zoom3, 9, 2, 1, 1)
        self.Zoom4 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Zoom4.sizePolicy().hasHeightForWidth())
        self.Zoom4.setSizePolicy(sizePolicy)
        self.Zoom4.setObjectName("Zoom4")
        self.gridLayout_4.addWidget(self.Zoom4, 9, 3, 1, 1)
        self.Transfermode = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Transfermode.sizePolicy().hasHeightForWidth())
        self.Transfermode.setSizePolicy(sizePolicy)
        self.Transfermode.setObjectName("Transfermode")
        self.gridLayout_4.addWidget(self.Transfermode, 14, 3, 1, 1)
        self.SampleViedo = QtWidgets.QGraphicsView(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SampleViedo.sizePolicy().hasHeightForWidth())
        self.SampleViedo.setSizePolicy(sizePolicy)
        self.SampleViedo.setMinimumSize(QtCore.QSize(320, 256))
        self.SampleViedo.setMaximumSize(QtCore.QSize(1280, 1024))
        self.SampleViedo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SampleViedo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SampleViedo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SampleViedo.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.SampleViedo.setObjectName("SampleViedo")
        self.gridLayout_4.addWidget(self.SampleViedo, 0, 0, 1, 4)
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 13, 0, 1, 4)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 11, 0, 1, 4)
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 8, 0, 1, 4)
        self.Focus_neg_s = QtWidgets.QPushButton(self.tab_2)
        self.Focus_neg_s.setObjectName("Focus_neg_s")
        self.gridLayout_4.addWidget(self.Focus_neg_s, 12, 1, 1, 1)
        self.Focus_pos_s = QtWidgets.QPushButton(self.tab_2)
        self.Focus_pos_s.setAutoRepeat(False)
        self.Focus_pos_s.setObjectName("Focus_pos_s")
        self.gridLayout_4.addWidget(self.Focus_pos_s, 12, 2, 1, 1)
        self.StartRaster = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartRaster.sizePolicy().hasHeightForWidth())
        self.StartRaster.setSizePolicy(sizePolicy)
        self.StartRaster.setMinimumSize(QtCore.QSize(0, 30))
        self.StartRaster.setIconSize(QtCore.QSize(16, 16))
        self.StartRaster.setObjectName("StartRaster")
        self.gridLayout_4.addWidget(self.StartRaster, 1, 2, 1, 2)
        self.Focus_neg_l = QtWidgets.QPushButton(self.tab_2)
        self.Focus_neg_l.setObjectName("Focus_neg_l")
        self.gridLayout_4.addWidget(self.Focus_neg_l, 12, 0, 1, 1)
        self.Focus_pos_l = QtWidgets.QPushButton(self.tab_2)
        self.Focus_pos_l.setAutoRepeat(False)
        self.Focus_pos_l.setObjectName("Focus_pos_l")
        self.gridLayout_4.addWidget(self.Focus_pos_l, 12, 3, 1, 1)
        self.Direct_collect = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Direct_collect.sizePolicy().hasHeightForWidth())
        self.Direct_collect.setSizePolicy(sizePolicy)
        self.Direct_collect.setMinimumSize(QtCore.QSize(0, 20))
        self.Direct_collect.setIconSize(QtCore.QSize(16, 16))
        self.Direct_collect.setObjectName("Direct_collect")
        self.gridLayout_4.addWidget(self.Direct_collect, 2, 2, 1, 2)
        self.Raster = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Raster.sizePolicy().hasHeightForWidth())
        self.Raster.setSizePolicy(sizePolicy)
        self.Raster.setMinimumSize(QtCore.QSize(0, 50))
        self.Raster.setIconSize(QtCore.QSize(16, 16))
        self.Raster.setObjectName("Raster")
        self.gridLayout_4.addWidget(self.Raster, 1, 0, 2, 2)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 2, 1)
        self.toolBox = QtWidgets.QToolBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(16777215, 130))
        self.toolBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolBox.setLineWidth(1)
        self.toolBox.setMidLineWidth(0)
        self.toolBox.setObjectName("toolBox")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 1149, 72))
        self.page_3.setObjectName("page_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.RootPath = QtWidgets.QLineEdit(self.page_3)
        self.RootPath.setObjectName("RootPath")
        self.gridLayout_12.addWidget(self.RootPath, 0, 0, 1, 1)
        self.RootPath_2 = QtWidgets.QLineEdit(self.page_3)
        self.RootPath_2.setEnabled(False)
        self.RootPath_2.setFrame(True)
        self.RootPath_2.setReadOnly(True)
        self.RootPath_2.setObjectName("RootPath_2")
        self.gridLayout_12.addWidget(self.RootPath_2, 1, 0, 1, 1)
        self.GetDefalutFolder = QtWidgets.QPushButton(self.page_3)
        self.GetDefalutFolder.setObjectName("GetDefalutFolder")
        self.gridLayout_12.addWidget(self.GetDefalutFolder, 0, 1, 1, 1)
        self.toolBox.addItem(self.page_3, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 1135, 73))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_5.sizePolicy().hasHeightForWidth())
        self.page_5.setSizePolicy(sizePolicy)
        self.page_5.setObjectName("page_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_16 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.gridLayout_10.addWidget(self.label_16, 0, 5, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout_10.addWidget(self.label_14, 0, 0, 1, 1)
        self.ExpouseValue = QtWidgets.QDoubleSpinBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExpouseValue.sizePolicy().hasHeightForWidth())
        self.ExpouseValue.setSizePolicy(sizePolicy)
        self.ExpouseValue.setDecimals(3)
        self.ExpouseValue.setMaximum(100.0)
        self.ExpouseValue.setProperty("value", 0.01)
        self.ExpouseValue.setObjectName("ExpouseValue")
        self.gridLayout_10.addWidget(self.ExpouseValue, 1, 2, 1, 1)
        self.ExpousetimeType = QtWidgets.QComboBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExpousetimeType.sizePolicy().hasHeightForWidth())
        self.ExpousetimeType.setSizePolicy(sizePolicy)
        self.ExpousetimeType.setMinimumSize(QtCore.QSize(110, 0))
        self.ExpousetimeType.setObjectName("ExpousetimeType")
        self.ExpousetimeType.addItem("")
        self.ExpousetimeType.addItem("")
        self.gridLayout_10.addWidget(self.ExpousetimeType, 0, 2, 1, 1)
        self.Attenuation = QtWidgets.QDoubleSpinBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Attenuation.sizePolicy().hasHeightForWidth())
        self.Attenuation.setSizePolicy(sizePolicy)
        self.Attenuation.setObjectName("Attenuation")
        self.gridLayout_10.addWidget(self.Attenuation, 1, 1, 1, 1)
        self.rasterdose = QtWidgets.QDoubleSpinBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rasterdose.sizePolicy().hasHeightForWidth())
        self.rasterdose.setSizePolicy(sizePolicy)
        self.rasterdose.setMinimumSize(QtCore.QSize(0, 0))
        self.rasterdose.setAlignment(QtCore.Qt.AlignCenter)
        self.rasterdose.setReadOnly(True)
        self.rasterdose.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.rasterdose.setDecimals(3)
        self.rasterdose.setObjectName("rasterdose")
        self.gridLayout_10.addWidget(self.rasterdose, 1, 8, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 0, 8, 1, 1)
        self.Distance = QtWidgets.QDoubleSpinBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Distance.sizePolicy().hasHeightForWidth())
        self.Distance.setSizePolicy(sizePolicy)
        self.Distance.setMinimum(140.0)
        self.Distance.setMaximum(1000.0)
        self.Distance.setObjectName("Distance")
        self.gridLayout_10.addWidget(self.Distance, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout_10.addWidget(self.label_13, 0, 1, 1, 1)
        self.selectGridsize = QtWidgets.QComboBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectGridsize.sizePolicy().hasHeightForWidth())
        self.selectGridsize.setSizePolicy(sizePolicy)
        self.selectGridsize.setMaxVisibleItems(11)
        self.selectGridsize.setObjectName("selectGridsize")
        self.selectGridsize.addItem("")
        self.selectGridsize.addItem("")
        self.selectGridsize.addItem("")
        self.selectGridsize.addItem("")
        self.selectGridsize.addItem("")
        self.selectGridsize.addItem("")
        self.selectGridsize.addItem("")
        self.selectGridsize.addItem("")
        self.selectGridsize.addItem("")
        self.selectGridsize.addItem("")
        self.selectGridsize.addItem("")
        self.gridLayout_10.addWidget(self.selectGridsize, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 0, 3, 1, 1)
        self.selectBeamsize = QtWidgets.QComboBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectBeamsize.sizePolicy().hasHeightForWidth())
        self.selectBeamsize.setSizePolicy(sizePolicy)
        self.selectBeamsize.setMaxVisibleItems(11)
        self.selectBeamsize.setObjectName("selectBeamsize")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.selectBeamsize.addItem("")
        self.gridLayout_10.addWidget(self.selectBeamsize, 1, 4, 1, 1)
        self.selectROI = QtWidgets.QComboBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectROI.sizePolicy().hasHeightForWidth())
        self.selectROI.setSizePolicy(sizePolicy)
        self.selectROI.setMaxVisibleItems(11)
        self.selectROI.setObjectName("selectROI")
        self.selectROI.addItem("")
        self.selectROI.addItem("")
        self.gridLayout_10.addWidget(self.selectROI, 1, 6, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.gridLayout_10.addWidget(self.label_17, 0, 4, 1, 1)
        self.RotationValue = QtWidgets.QDoubleSpinBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RotationValue.sizePolicy().hasHeightForWidth())
        self.RotationValue.setSizePolicy(sizePolicy)
        self.RotationValue.setDecimals(3)
        self.RotationValue.setMaximum(10.0)
        self.RotationValue.setSingleStep(0.1)
        self.RotationValue.setProperty("value", 0.0)
        self.RotationValue.setObjectName("RotationValue")
        self.gridLayout_10.addWidget(self.RotationValue, 1, 5, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 0, 6, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName("label_26")
        self.gridLayout_10.addWidget(self.label_26, 0, 7, 1, 1)
        self.select2scan = QtWidgets.QComboBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select2scan.sizePolicy().hasHeightForWidth())
        self.select2scan.setSizePolicy(sizePolicy)
        self.select2scan.setMaxVisibleItems(11)
        self.select2scan.setObjectName("select2scan")
        self.select2scan.addItem("")
        self.select2scan.addItem("")
        self.gridLayout_10.addWidget(self.select2scan, 1, 7, 1, 1)
        self.gridLayout_10.setColumnStretch(0, 5)
        self.gridLayout_10.setColumnStretch(1, 10)
        self.gridLayout_10.setColumnStretch(2, 10)
        self.gridLayout_10.setColumnStretch(3, 10)
        self.gridLayout_10.setColumnStretch(4, 10)
        self.gridLayout_10.setColumnStretch(5, 5)
        self.gridLayout_10.setColumnStretch(6, 5)
        self.gridLayout_10.setColumnStretch(7, 5)
        self.verticalLayout_7.addLayout(self.gridLayout_10)
        self.toolBox.addItem(self.page_5, "")
        self.gridLayout_5.addWidget(self.toolBox, 0, 2, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.RasterView1 = QtWidgets.QGraphicsView(self.tab_2)
        self.RasterView1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RasterView1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RasterView1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.RasterView1.setViewportUpdateMode(QtWidgets.QGraphicsView.SmartViewportUpdate)
        self.RasterView1.setObjectName("RasterView1")
        self.verticalLayout.addWidget(self.RasterView1)
        self.Overlap_Select_1 = QtWidgets.QComboBox(self.tab_2)
        self.Overlap_Select_1.setObjectName("Overlap_Select_1")
        self.Overlap_Select_1.addItem("")
        self.Overlap_Select_1.addItem("")
        self.Overlap_Select_1.addItem("")
        self.Overlap_Select_1.addItem("")
        self.Overlap_Select_1.addItem("")
        self.Overlap_Select_1.addItem("")
        self.Overlap_Select_1.addItem("")
        self.verticalLayout.addWidget(self.Overlap_Select_1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.view1_opacity = QtWidgets.QSlider(self.tab_2)
        self.view1_opacity.setMaximum(100)
        self.view1_opacity.setProperty("value", 80)
        self.view1_opacity.setOrientation(QtCore.Qt.Horizontal)
        self.view1_opacity.setObjectName("view1_opacity")
        self.horizontalLayout_7.addWidget(self.view1_opacity)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_3.addWidget(self.label_22)
        self.updatelist_1 = QtWidgets.QComboBox(self.tab_2)
        self.updatelist_1.setObjectName("updatelist_1")
        self.updatelist_1.addItem("")
        self.updatelist_1.addItem("")
        self.updatelist_1.addItem("")
        self.horizontalLayout_3.addWidget(self.updatelist_1)
        self.ClearAll_1 = QtWidgets.QPushButton(self.tab_2)
        self.ClearAll_1.setObjectName("ClearAll_1")
        self.horizontalLayout_3.addWidget(self.ClearAll_1)
        self.EditPos_1 = QtWidgets.QPushButton(self.tab_2)
        self.EditPos_1.setCheckable(True)
        self.EditPos_1.setObjectName("EditPos_1")
        self.horizontalLayout_3.addWidget(self.EditPos_1)
        self.MovePos_1 = QtWidgets.QPushButton(self.tab_2)
        self.MovePos_1.setCheckable(True)
        self.MovePos_1.setObjectName("MovePos_1")
        self.horizontalLayout_3.addWidget(self.MovePos_1)
        self.horizontalLayout_3.setStretch(1, 10)
        self.horizontalLayout_3.setStretch(2, 10)
        self.horizontalLayout_3.setStretch(3, 10)
        self.horizontalLayout_3.setStretch(4, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.List_number_1 = QtWidgets.QSpinBox(self.tab_2)
        self.List_number_1.setMaximum(999)
        self.List_number_1.setProperty("value", 10)
        self.List_number_1.setObjectName("List_number_1")
        self.horizontalLayout_2.addWidget(self.List_number_1)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.Threshold_1 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.Threshold_1.setMinimum(-1.0)
        self.Threshold_1.setMaximum(9999.0)
        self.Threshold_1.setProperty("value", 1.0)
        self.Threshold_1.setObjectName("Threshold_1")
        self.horizontalLayout_2.addWidget(self.Threshold_1)
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_2.addWidget(self.label_19)
        self.Min_peak_distance_1 = QtWidgets.QSpinBox(self.tab_2)
        self.Min_peak_distance_1.setMaximum(999)
        self.Min_peak_distance_1.setProperty("value", 0)
        self.Min_peak_distance_1.setObjectName("Min_peak_distance_1")
        self.horizontalLayout_2.addWidget(self.Min_peak_distance_1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.viwe1_move_down = QtWidgets.QPushButton(self.tab_2)
        self.viwe1_move_down.setObjectName("viwe1_move_down")
        self.gridLayout_3.addWidget(self.viwe1_move_down, 2, 1, 1, 1)
        self.viwe1_move_up = QtWidgets.QPushButton(self.tab_2)
        self.viwe1_move_up.setObjectName("viwe1_move_up")
        self.gridLayout_3.addWidget(self.viwe1_move_up, 0, 1, 1, 1)
        self.viwe1_move_right = QtWidgets.QPushButton(self.tab_2)
        self.viwe1_move_right.setAutoRepeat(False)
        self.viwe1_move_right.setObjectName("viwe1_move_right")
        self.gridLayout_3.addWidget(self.viwe1_move_right, 1, 2, 1, 1)
        self.collectAllpos_1 = QtWidgets.QPushButton(self.tab_2)
        self.collectAllpos_1.setObjectName("collectAllpos_1")
        self.gridLayout_3.addWidget(self.collectAllpos_1, 3, 2, 1, 1)
        self.DetailInfo1 = QtWidgets.QPushButton(self.tab_2)
        self.DetailInfo1.setObjectName("DetailInfo1")
        self.gridLayout_3.addWidget(self.DetailInfo1, 3, 0, 1, 1)
        self.viwe1_move_left = QtWidgets.QPushButton(self.tab_2)
        self.viwe1_move_left.setObjectName("viwe1_move_left")
        self.gridLayout_3.addWidget(self.viwe1_move_left, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_5.addLayout(self.verticalLayout, 1, 2, 3, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.RasterView2 = QtWidgets.QGraphicsView(self.tab_2)
        self.RasterView2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RasterView2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RasterView2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.RasterView2.setViewportUpdateMode(QtWidgets.QGraphicsView.SmartViewportUpdate)
        self.RasterView2.setObjectName("RasterView2")
        self.verticalLayout_3.addWidget(self.RasterView2)
        self.Overlap_Select_2 = QtWidgets.QComboBox(self.tab_2)
        self.Overlap_Select_2.setObjectName("Overlap_Select_2")
        self.Overlap_Select_2.addItem("")
        self.Overlap_Select_2.addItem("")
        self.Overlap_Select_2.addItem("")
        self.Overlap_Select_2.addItem("")
        self.Overlap_Select_2.addItem("")
        self.Overlap_Select_2.addItem("")
        self.Overlap_Select_2.addItem("")
        self.verticalLayout_3.addWidget(self.Overlap_Select_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.view2_opacity = QtWidgets.QSlider(self.tab_2)
        self.view2_opacity.setMaximum(100)
        self.view2_opacity.setProperty("value", 80)
        self.view2_opacity.setOrientation(QtCore.Qt.Horizontal)
        self.view2_opacity.setObjectName("view2_opacity")
        self.horizontalLayout_8.addWidget(self.view2_opacity)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_4.addWidget(self.label_23)
        self.updatelist_2 = QtWidgets.QComboBox(self.tab_2)
        self.updatelist_2.setObjectName("updatelist_2")
        self.updatelist_2.addItem("")
        self.updatelist_2.addItem("")
        self.updatelist_2.addItem("")
        self.horizontalLayout_4.addWidget(self.updatelist_2)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.ClearAll_2 = QtWidgets.QPushButton(self.tab_2)
        self.ClearAll_2.setObjectName("ClearAll_2")
        self.horizontalLayout_4.addWidget(self.ClearAll_2)
        self.EditPos_2 = QtWidgets.QPushButton(self.tab_2)
        self.EditPos_2.setCheckable(True)
        self.EditPos_2.setObjectName("EditPos_2")
        self.horizontalLayout_4.addWidget(self.EditPos_2)
        self.MovePos_2 = QtWidgets.QPushButton(self.tab_2)
        self.MovePos_2.setCheckable(True)
        self.MovePos_2.setObjectName("MovePos_2")
        self.horizontalLayout_4.addWidget(self.MovePos_2)
        self.horizontalLayout_4.setStretch(1, 10)
        self.horizontalLayout_4.setStretch(3, 10)
        self.horizontalLayout_4.setStretch(4, 10)
        self.horizontalLayout_4.setStretch(5, 10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.List_number_2 = QtWidgets.QSpinBox(self.tab_2)
        self.List_number_2.setMaximum(999)
        self.List_number_2.setProperty("value", 10)
        self.List_number_2.setObjectName("List_number_2")
        self.horizontalLayout_5.addWidget(self.List_number_2)
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_5.addWidget(self.label_20)
        self.Threshold_2 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.Threshold_2.setMinimum(-1.0)
        self.Threshold_2.setMaximum(9999.0)
        self.Threshold_2.setProperty("value", 1.0)
        self.Threshold_2.setObjectName("Threshold_2")
        self.horizontalLayout_5.addWidget(self.Threshold_2)
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_5.addWidget(self.label_21)
        self.Min_peak_distance_2 = QtWidgets.QSpinBox(self.tab_2)
        self.Min_peak_distance_2.setMaximum(999)
        self.Min_peak_distance_2.setProperty("value", 0)
        self.Min_peak_distance_2.setObjectName("Min_peak_distance_2")
        self.horizontalLayout_5.addWidget(self.Min_peak_distance_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.viwe2_move_up = QtWidgets.QPushButton(self.tab_2)
        self.viwe2_move_up.setObjectName("viwe2_move_up")
        self.gridLayout_11.addWidget(self.viwe2_move_up, 0, 1, 1, 1)
        self.viwe2_move_right = QtWidgets.QPushButton(self.tab_2)
        self.viwe2_move_right.setObjectName("viwe2_move_right")
        self.gridLayout_11.addWidget(self.viwe2_move_right, 1, 2, 1, 1)
        self.viwe2_move_left = QtWidgets.QPushButton(self.tab_2)
        self.viwe2_move_left.setObjectName("viwe2_move_left")
        self.gridLayout_11.addWidget(self.viwe2_move_left, 1, 0, 1, 1)
        self.viwe2_move_down = QtWidgets.QPushButton(self.tab_2)
        self.viwe2_move_down.setObjectName("viwe2_move_down")
        self.gridLayout_11.addWidget(self.viwe2_move_down, 2, 1, 1, 1)
        self.collectAllpos_2 = QtWidgets.QPushButton(self.tab_2)
        self.collectAllpos_2.setObjectName("collectAllpos_2")
        self.gridLayout_11.addWidget(self.collectAllpos_2, 3, 2, 1, 1)
        self.DetailInfo2 = QtWidgets.QPushButton(self.tab_2)
        self.DetailInfo2.setObjectName("DetailInfo2")
        self.gridLayout_11.addWidget(self.DetailInfo2, 3, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_11)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 1, 3, 3, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 2, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.hutchvideo1 = QtWidgets.QGraphicsView(self.tab_2)
        self.hutchvideo1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.hutchvideo1.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.hutchvideo1.setTransformationAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.hutchvideo1.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.hutchvideo1.setObjectName("hutchvideo1")
        self.verticalLayout_6.addWidget(self.hutchvideo1)
        self.hutchvideo1_scale = QtWidgets.QSlider(self.tab_2)
        self.hutchvideo1_scale.setMinimum(0)
        self.hutchvideo1_scale.setMaximum(100)
        self.hutchvideo1_scale.setOrientation(QtCore.Qt.Horizontal)
        self.hutchvideo1_scale.setObjectName("hutchvideo1_scale")
        self.verticalLayout_6.addWidget(self.hutchvideo1_scale)
        self.hutchvideo2 = QtWidgets.QGraphicsView(self.tab_2)
        self.hutchvideo2.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.hutchvideo2.setTransformationAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.hutchvideo2.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.hutchvideo2.setObjectName("hutchvideo2")
        self.verticalLayout_6.addWidget(self.hutchvideo2)
        self.hutchvideo2_scale = QtWidgets.QSlider(self.tab_2)
        self.hutchvideo2_scale.setMinimum(0)
        self.hutchvideo2_scale.setMaximum(100)
        self.hutchvideo2_scale.setOrientation(QtCore.Qt.Horizontal)
        self.hutchvideo2_scale.setObjectName("hutchvideo2_scale")
        self.verticalLayout_6.addWidget(self.hutchvideo2_scale)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout_6.addLayout(self.gridLayout_13)
        self.verticalLayout_6.setStretch(0, 100)
        self.verticalLayout_6.setStretch(2, 100)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 3, 0, 1, 1)
        self.gridLayout_5.setRowMinimumHeight(0, 140)
        self.gridLayout_5.setColumnStretch(2, 50)
        self.gridLayout_5.setColumnStretch(3, 50)
        self.tabWidget.addTab(self.tab_2, "")
        self.Option = QtWidgets.QWidget()
        self.Option.setObjectName("Option")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Option)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_25 = QtWidgets.QLabel(self.Option)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 0, 0, 1, 1)
        self.Raster_scoring_way = QtWidgets.QComboBox(self.Option)
        self.Raster_scoring_way.setObjectName("Raster_scoring_way")
        self.Raster_scoring_way.addItem("")
        self.Raster_scoring_way.addItem("")
        self.gridLayout_6.addWidget(self.Raster_scoring_way, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Option, "")
        self.Collect = QtWidgets.QWidget()
        self.Collect.setObjectName("Collect")
        self.tabWidget.addTab(self.Collect, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.debug_raster = QtWidgets.QPushButton(self.tab)
        self.debug_raster.setObjectName("debug_raster")
        self.gridLayout_8.addWidget(self.debug_raster, 2, 0, 1, 1)
        self.debug_operation = QtWidgets.QPushButton(self.tab)
        self.debug_operation.setObjectName("debug_operation")
        self.gridLayout_8.addWidget(self.debug_operation, 1, 0, 1, 1)
        self.debug_string = QtWidgets.QPushButton(self.tab)
        self.debug_string.setObjectName("debug_string")
        self.gridLayout_8.addWidget(self.debug_string, 0, 1, 1, 1)
        self.debug_motor = QtWidgets.QPushButton(self.tab)
        self.debug_motor.setObjectName("debug_motor")
        self.gridLayout_8.addWidget(self.debug_motor, 0, 0, 1, 1)
        self.debug_shutter = QtWidgets.QPushButton(self.tab)
        self.debug_shutter.setObjectName("debug_shutter")
        self.gridLayout_8.addWidget(self.debug_shutter, 1, 1, 1, 1)
        self.debug_Debug = QtWidgets.QPushButton(self.tab)
        self.debug_Debug.setObjectName("debug_Debug")
        self.gridLayout_8.addWidget(self.debug_Debug, 2, 1, 1, 1)
        self.debug_loaddata = QtWidgets.QPushButton(self.tab)
        self.debug_loaddata.setObjectName("debug_loaddata")
        self.gridLayout_8.addWidget(self.debug_loaddata, 3, 0, 1, 1)
        self.RecollectRaster = QtWidgets.QPushButton(self.tab)
        self.RecollectRaster.setObjectName("RecollectRaster")
        self.gridLayout_8.addWidget(self.RecollectRaster, 3, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1654, 20))
        self.menubar.setObjectName("menubar")
        self.menuMeshBestGUI = QtWidgets.QMenu(self.menubar)
        self.menuMeshBestGUI.setObjectName("menuMeshBestGUI")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuMeshBestGUI.addSeparator()
        self.menubar.addAction(self.menuMeshBestGUI.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(1)
        self.selectGridsize.setCurrentIndex(8)
        self.selectBeamsize.setCurrentIndex(10)
        self.selectROI.setCurrentIndex(0)
        self.select2scan.setCurrentIndex(0)
        self.Overlap_Select_1.setCurrentIndex(1)
        self.Overlap_Select_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mesh and Collect"))
        self.LastInfo.setText(_translate("MainWindow", "LastInfo"))
        self.label.setText(_translate("MainWindow", "TPS State:"))
        self.TPSStateText.setText(_translate("MainWindow", "Open"))
        self.Current.setSuffix(_translate("MainWindow", " mA"))
        self.label_2.setText(_translate("MainWindow", "Energy:"))
        self.Energy.setSuffix(_translate("MainWindow", " ev"))
        self.label_6.setText(_translate("MainWindow", "Beamline flux:"))
        self.beamlineflux.setText(_translate("MainWindow", "0 phs/sec"))
        self.label_24.setText(_translate("MainWindow", "Time to Injection:"))
        self.timetoinj.setText(_translate("MainWindow", "-1 sec"))
        self.Abort.setText(_translate("MainWindow", "Abort"))
        self.Active.setText(_translate("MainWindow", "Unknow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "I has no idea....."))
        self.comboBox.setItemText(1, _translate("MainWindow", "Single Crystal"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Small wedge"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Project Setup"))
        self.Autocenter.setText(_translate("MainWindow", "Auto Center"))
        self.Zoom1.setText(_translate("MainWindow", "Zoom1"))
        self.pos_10deg.setText(_translate("MainWindow", "+10deg"))
        self.pos_90deg.setText(_translate("MainWindow", "+90deg"))
        self.Centermode.setText(_translate("MainWindow", "Center mode"))
        self.Zoom2.setText(_translate("MainWindow", "Zoom2"))
        self.neg_90deg.setText(_translate("MainWindow", "-90deg"))
        self.neg_10deg.setText(_translate("MainWindow", "-10deg"))
        self.Zoom3.setText(_translate("MainWindow", "Zoom3"))
        self.Zoom4.setText(_translate("MainWindow", "Zoom4"))
        self.Transfermode.setText(_translate("MainWindow", "Transfer mode"))
        self.label_7.setText(_translate("MainWindow", "Focus Centering"))
        self.Focus_neg_s.setText(_translate("MainWindow", "<"))
        self.Focus_pos_s.setText(_translate("MainWindow", ">"))
        self.StartRaster.setText(_translate("MainWindow", "Start Raster"))
        self.Focus_neg_l.setText(_translate("MainWindow", "<<"))
        self.Focus_pos_l.setText(_translate("MainWindow", ">>"))
        self.Direct_collect.setText(_translate("MainWindow", "Direct Fixed Target Serial Data Collect"))
        self.Raster.setText(_translate("MainWindow", "Take Raster Image"))
        self.GetDefalutFolder.setText(_translate("MainWindow", "Defalut"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "File Setup"))
        self.label_16.setText(_translate("MainWindow", "Rotation"))
        self.label_14.setText(_translate("MainWindow", "Detector Distance"))
        self.ExpousetimeType.setItemText(0, _translate("MainWindow", "Exposure time"))
        self.ExpousetimeType.setItemText(1, _translate("MainWindow", "Rate"))
        self.rasterdose.setSuffix(_translate("MainWindow", "Mgy"))
        self.label_15.setText(_translate("MainWindow", "Dose"))
        self.label_13.setText(_translate("MainWindow", "Attenuation"))
        self.selectGridsize.setCurrentText(_translate("MainWindow", "20"))
        self.selectGridsize.setItemText(0, _translate("MainWindow", "100"))
        self.selectGridsize.setItemText(1, _translate("MainWindow", "90"))
        self.selectGridsize.setItemText(2, _translate("MainWindow", "80"))
        self.selectGridsize.setItemText(3, _translate("MainWindow", "70"))
        self.selectGridsize.setItemText(4, _translate("MainWindow", "60"))
        self.selectGridsize.setItemText(5, _translate("MainWindow", "50"))
        self.selectGridsize.setItemText(6, _translate("MainWindow", "40"))
        self.selectGridsize.setItemText(7, _translate("MainWindow", "30"))
        self.selectGridsize.setItemText(8, _translate("MainWindow", "20"))
        self.selectGridsize.setItemText(9, _translate("MainWindow", "10"))
        self.selectGridsize.setItemText(10, _translate("MainWindow", "5"))
        self.label_12.setText(_translate("MainWindow", "GirdSize"))
        self.selectBeamsize.setCurrentText(_translate("MainWindow", "5"))
        self.selectBeamsize.setItemText(0, _translate("MainWindow", "100"))
        self.selectBeamsize.setItemText(1, _translate("MainWindow", "90"))
        self.selectBeamsize.setItemText(2, _translate("MainWindow", "80"))
        self.selectBeamsize.setItemText(3, _translate("MainWindow", "70"))
        self.selectBeamsize.setItemText(4, _translate("MainWindow", "60"))
        self.selectBeamsize.setItemText(5, _translate("MainWindow", "50"))
        self.selectBeamsize.setItemText(6, _translate("MainWindow", "40"))
        self.selectBeamsize.setItemText(7, _translate("MainWindow", "30"))
        self.selectBeamsize.setItemText(8, _translate("MainWindow", "20"))
        self.selectBeamsize.setItemText(9, _translate("MainWindow", "10"))
        self.selectBeamsize.setItemText(10, _translate("MainWindow", "5"))
        self.selectBeamsize.setItemText(11, _translate("MainWindow", "1"))
        self.selectROI.setCurrentText(_translate("MainWindow", "Enable"))
        self.selectROI.setItemText(0, _translate("MainWindow", "Enable"))
        self.selectROI.setItemText(1, _translate("MainWindow", "Disable"))
        self.label_17.setText(_translate("MainWindow", "Beamsize"))
        self.label_18.setText(_translate("MainWindow", "ROI"))
        self.label_26.setText(_translate("MainWindow", "Scan 2 view"))
        self.select2scan.setCurrentText(_translate("MainWindow", "Enable"))
        self.select2scan.setItemText(0, _translate("MainWindow", "Enable"))
        self.select2scan.setItemText(1, _translate("MainWindow", "Disable"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "Raster scan Par"))
        self.Overlap_Select_1.setItemText(0, _translate("MainWindow", "None"))
        self.Overlap_Select_1.setItemText(1, _translate("MainWindow", "Grid"))
        self.Overlap_Select_1.setItemText(2, _translate("MainWindow", "Dozor score"))
        self.Overlap_Select_1.setItemText(3, _translate("MainWindow", "Number of Peaks"))
        self.Overlap_Select_1.setItemText(4, _translate("MainWindow", "Visible resolution"))
        self.Overlap_Select_1.setItemText(5, _translate("MainWindow", "Crystal Map"))
        self.Overlap_Select_1.setItemText(6, _translate("MainWindow", "Crystal Map with Dozor score"))
        self.label_8.setText(_translate("MainWindow", "Opacity(%)"))
        self.label_22.setText(_translate("MainWindow", "Position pick"))
        self.updatelist_1.setItemText(0, _translate("MainWindow", "Meshbest"))
        self.updatelist_1.setItemText(1, _translate("MainWindow", "Manual"))
        self.updatelist_1.setItemText(2, _translate("MainWindow", "base on peak number"))
        self.ClearAll_1.setText(_translate("MainWindow", "Clear All"))
        self.EditPos_1.setText(_translate("MainWindow", "Add/Del Pos."))
        self.MovePos_1.setText(_translate("MainWindow", "Move Pos."))
        self.label_4.setText(_translate("MainWindow", "MaxNumber"))
        self.label_11.setText(_translate("MainWindow", "Threshold"))
        self.label_19.setText(_translate("MainWindow", "Min distance between peak"))
        self.viwe1_move_down.setText(_translate("MainWindow", "v"))
        self.viwe1_move_up.setText(_translate("MainWindow", "^"))
        self.viwe1_move_right.setText(_translate("MainWindow", ">"))
        self.collectAllpos_1.setText(_translate("MainWindow", "Collect All Position"))
        self.DetailInfo1.setText(_translate("MainWindow", "Display collect info"))
        self.viwe1_move_left.setText(_translate("MainWindow", "<"))
        self.Overlap_Select_2.setItemText(0, _translate("MainWindow", "None"))
        self.Overlap_Select_2.setItemText(1, _translate("MainWindow", "Grid"))
        self.Overlap_Select_2.setItemText(2, _translate("MainWindow", "Dozor score"))
        self.Overlap_Select_2.setItemText(3, _translate("MainWindow", "Number of Peaks"))
        self.Overlap_Select_2.setItemText(4, _translate("MainWindow", "Visible resolution"))
        self.Overlap_Select_2.setItemText(5, _translate("MainWindow", "Crystal Map"))
        self.Overlap_Select_2.setItemText(6, _translate("MainWindow", "Crystal Map with Dozor score"))
        self.label_9.setText(_translate("MainWindow", "Opacity(%)"))
        self.label_23.setText(_translate("MainWindow", "Position pick"))
        self.updatelist_2.setItemText(0, _translate("MainWindow", "Meshbest"))
        self.updatelist_2.setItemText(1, _translate("MainWindow", "Manual"))
        self.updatelist_2.setItemText(2, _translate("MainWindow", "base on peak number"))
        self.label_5.setText(_translate("MainWindow", "Listnumber"))
        self.ClearAll_2.setText(_translate("MainWindow", "Clear All"))
        self.EditPos_2.setText(_translate("MainWindow", "Add/Del Pos."))
        self.MovePos_2.setText(_translate("MainWindow", "Move Pos."))
        self.label_10.setText(_translate("MainWindow", "MaxNumber"))
        self.label_20.setText(_translate("MainWindow", "Threshold"))
        self.label_21.setText(_translate("MainWindow", "Min distance between peak"))
        self.viwe2_move_up.setText(_translate("MainWindow", "^"))
        self.viwe2_move_right.setText(_translate("MainWindow", ">"))
        self.viwe2_move_left.setText(_translate("MainWindow", "<"))
        self.viwe2_move_down.setText(_translate("MainWindow", "v"))
        self.collectAllpos_2.setText(_translate("MainWindow", "Collect All Position"))
        self.DetailInfo2.setText(_translate("MainWindow", "Display collect info"))
        self.label_3.setText(_translate("MainWindow", "Hutch video"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Crystal Center and Raster"))
        self.label_25.setText(_translate("MainWindow", "Raster scan scoring"))
        self.Raster_scoring_way.setItemText(0, _translate("MainWindow", "Dozor"))
        self.Raster_scoring_way.setItemText(1, _translate("MainWindow", "None"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Option), _translate("MainWindow", "Option"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Collect), _translate("MainWindow", "Collect"))
        self.debug_raster.setText(_translate("MainWindow", "Raster"))
        self.debug_operation.setText(_translate("MainWindow", "operation"))
        self.debug_string.setText(_translate("MainWindow", "string"))
        self.debug_motor.setText(_translate("MainWindow", "Motor"))
        self.debug_shutter.setText(_translate("MainWindow", "shutter"))
        self.debug_Debug.setText(_translate("MainWindow", "Debug"))
        self.debug_loaddata.setText(_translate("MainWindow", "Load data"))
        self.RecollectRaster.setText(_translate("MainWindow", "RecollectRaster"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Debug"))
        self.menuMeshBestGUI.setTitle(_translate("MainWindow", "Experiment"))

