# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CollectPar.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.setEnabled(True)
        Dialog.resize(1143, 493)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(200, 300))
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 22, 1121, 461))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Strategy = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.Strategy.setFont(font)
        self.Strategy.setObjectName("Strategy")
        self.Strategy.addItem("")
        self.Strategy.addItem("")
        self.Strategy.addItem("")
        self.verticalLayout.addWidget(self.Strategy)
        self.InfoTable = QtWidgets.QTableWidget(self.layoutWidget)
        self.InfoTable.setShowGrid(True)
        self.InfoTable.setColumnCount(11)
        self.InfoTable.setObjectName("InfoTable")
        self.InfoTable.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.InfoTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.InfoTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.InfoTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.InfoTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.InfoTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.InfoTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.InfoTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.InfoTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.InfoTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.InfoTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.InfoTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.InfoTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.InfoTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.InfoTable.setHorizontalHeaderItem(10, item)
        self.InfoTable.horizontalHeader().setVisible(True)
        self.InfoTable.horizontalHeader().setCascadingSectionResizes(True)
        self.InfoTable.horizontalHeader().setDefaultSectionSize(100)
        self.InfoTable.horizontalHeader().setSortIndicatorShown(False)
        self.InfoTable.horizontalHeader().setStretchLastSection(False)
        self.InfoTable.verticalHeader().setVisible(True)
        self.InfoTable.verticalHeader().setCascadingSectionResizes(False)
        self.InfoTable.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.InfoTable)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.YesToAll)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Collect Par."))
        self.Strategy.setItemText(0, _translate("Dialog", "Auto"))
        self.Strategy.setItemText(1, _translate("Dialog", "By Rough dose"))
        self.Strategy.setItemText(2, _translate("Dialog", "Manual"))
        item = self.InfoTable.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.InfoTable.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.InfoTable.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.InfoTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "X"))
        item = self.InfoTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Y"))
        item = self.InfoTable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Beamsize"))
        item = self.InfoTable.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Rough dose(by Holton)"))
        item = self.InfoTable.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Estimate dose"))
        item = self.InfoTable.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Atten%"))
        item = self.InfoTable.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Exposed Time"))
        item = self.InfoTable.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Total collect range"))
        item = self.InfoTable.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "Frame width"))
        item = self.InfoTable.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "Distance"))
        item = self.InfoTable.horizontalHeaderItem(10)
        item.setText(_translate("Dialog", "Energy"))
